### ISSUE TITLE
those code in new sms or spk option seems missed something?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [vim/vim#11282]
### Steps to reproduce

1, vim --clean foo.md
2, vnew
3, jump the cursor back to foo.md window
4, keep pressing  j/k to move some 
// the screen became mess after so..

the foo.md:
// something like this, i do not understand those 'words' meaning, supposed no sensitive words
```markdown
<kbd>[<img title="Limba Română" alt="Limba Română" src="foo" width="22">](translations/README.ro.md)</kbd>
<kbd>[<img title="မြန်မာ" alt="မြန်မာ" src="foo" width="22">](translations/README.mm_unicode.md)</kbd>
<kbd>[<img title="Македонски" alt="Македонски" src="foo" width="22">](translations/README.mk.md)</kbd>
<kbd>[<img title="Español de México" alt="Español de México" src="foo" width="22">](translations/README.mx.md)</kbd>
<kbd>[<img title="Bahasa Melayu / بهاس ملايو‎ / Malay" alt="Bahasa Melayu / بهاس ملايو‎ / Malay" src="foo" width="22">](translations/README.my.md)</kbd>
<kbd>[<img title="Dutch" alt="Dutch" src="foo" width="22">](translations/README.nl.md)</kbd>
```

### Expected behaviour

no stray chars

### Version of Vim

v9.0.656

### Environment

linux
xfce-term

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/193853457-0c3b7a59-c7c0-4a26-a13e-a829055d53dc.png)

**Comment by brammool** [comment]
I cannot follow these reproduction steps.  Can you check if patch 9.0.0662 has fixed this?
If not, please try to give a simpler example.

**Comment by Shane-XB-Qian** [comment]
> Can you check if patch 9.0.0662 has fixed this?

no, issue still there.

------

how about this:
```vim
 vim --clean foo.md -c 'set columns=160 | exe "normal ggVGypppppp" | vnew | wincmd l | rightbelow vsp | wincmd h | normal ggjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkjjjjjjjjkkkkkkkkkkk'
```

**Comment by brammool** [comment]
I can reproduce a problem in xterm with just one line and a vertical split.
The problem appears to be that Vim considers character 4156 (0x103c) to be a composing character, but the terminal doesn't.
The text then takes more space and overflows to the next line.

I think this is a mistake in the unicode table, "spacing combining" take up space, thus should not be considered "composing" characters.

**Comment by Shane-XB-Qian** [comment]
![image](https://user-images.githubusercontent.com/13550529/194108134-c41747a4-21a8-4cc1-b7a5-68298a87aa53.png)

tried with xterm(372), even `set nowrap` (i was thinking that was a matter), but looks worse..

**Comment by Shane-XB-Qian** [comment]
except english and chinese, no idea those words meaning, but i do guess that was the matter too
but not sure which one.. :-) out of my knowledge... :-(

**Comment by brammool** [comment]
Fixed with patch 9.0.0666
That character is from Myanmar.

**Comment by Shane-XB-Qian** [comment]
seems partially fixed, but:

// seems worse:
if running within a `gun-screen`

// seems not fixed:
if file name is those `chars`, (and tabline or stl was set to show its filename)

#10523 
// seems related, though maybe more about was a gnu-screen issue.

**Comment by brammool** [comment]
The "screen" program indeed makes this look bad.  Since it only happens with "screen" I can only assume this is a problem in "screen".  tmux works fine.

**Comment by Shane-XB-Qian** [comment]
but looks this made the file which having multiple width chars in filename (would be set to display at tabline or stl, specially had long name) and/or content be more easier displaying with stray chars.
// had to wait Gun-screen fix this? but seems that's a very inactive proj.

--
shane.xb.qian
