### ISSUE TITLE
If 'list' is on, 'below' virtual text which includes 1 or 2 characters are gone

### ISSUE THREAD

**Issue by rickhowe** [vim/vim#12028]
If text is a single character and draw the "below" virtual line.

![44](https://user-images.githubusercontent.com/3096934/218414052-9e1e6764-c2fb-4ce8-b65a-a6c7665976e5.png)

Then &list is set, all the virtual lines are gone.

![55](https://user-images.githubusercontent.com/3096934/218414347-c8039172-2d6e-4500-a64b-38c4aca66d53.png)

If "above", looks like no problem.

![66](https://user-images.githubusercontent.com/3096934/218415384-3dddf85f-c260-4c1c-b6f6-12f04f5eb7bc.png)

And if "below", the problem happens only if text is 1 or 2 characters.

![77](https://user-images.githubusercontent.com/3096934/218417020-3702afdb-855a-4464-972d-08cf98b8e3da.png)

**Comment by rickhowe** [comment]
I found that I forgot to mention about the link to [related problem](https://github.com/vim/vim/issues/11959#issuecomment-1427589736).

**Comment by dylanahsmith** [comment]
I opened a fix for the related problem https://github.com/vim/vim/pull/14096, but didn't notice this problem when testing that, where this issue seems to share the same test script.

Am I right that this has been fixed already?

**Comment by rickhowe** [comment]
Not completely fixed.

I tested on 9.1.0139.
```
call setline(1, ['11111', '', '33333', '', '55555'])
set number
let vt = 'test'
call prop_type_add(vt, {'highlight': 'ToDo'})
for ln in range(1, line('$'))
  call prop_add(ln, 0, {'type': vt, 'text': '+', 'text_align': 'below'})
endfor
```
Then `:set list`. Screen looks OK, but if press `j` to move cursor  to the 2nd line:

![image](https://github.com/vim/vim/assets/3096934/ace2f535-52e7-4de4-b55e-213afcb3b1b6)

The cursor is incorrectly moved on to the virtual text. Same things happen if virtual text is 2 characters, but no  problem for 3 or more characters

If 'above', no problem for screen and cursor.

**Comment by dylanahsmith** [comment]
That's the problem my fix (#14096) addresses, so it looks like this issue can be closed by that fix.

**Comment by dylanahsmith** [comment]
> The cursor is incorrectly moved on to the virtual text. Same things happen if virtual text is 2 characters

Actually, I don't see the problem on master (which does seem to be tagged v9.1.0139) when the virtual text is 2 characters, only when it is 1 character long.

**Comment by rickhowe** [comment]
I checked again. When using `gk` and/or `gj`, cursor is moved on to the last character on the line, not on to the next line..  That happens even if the length of virtual text is more than 1. `j` and/or `k` work fine.

**Comment by chrisbra** [comment]
Yeah, I noticed one needs to press `gk` /`gj` several times until the cursor moves up a line (you can see in the ruler how the byte column changes until it goes eventually up/down). I suppose going by screen line is confusing enough for text properties that seem to occupy a whole line by themselves. 
That one does not seem to be fixed by #14096

**Comment by dylanahsmith** [comment]
> When using gk and/or gj, cursor is moved on to the last character on the line, not on to the next line.

Thanks for pointing out this issue, I'll look into it.

Note that this `gk`/`gj` issue doesn't seem to depend on the same conditions:
* it happens even with longer than 2 character virtual text (e.g. with `+++`)
* it happens even with `set nolist`
* it happens even with `'above'` virtual text
