### ISSUE TITLE
`command -complete=file`  ignore E194

### ISSUE THREAD

**Issue by yu3s** [vim/vim#14934]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**
1. `cat test.vim`
```vim
vim9script

command! -nargs=+ -complete=file Rg :echo '<args>'
```
2. `vim --clean -c "so ./test.vim | Rg #if ./"`

**Describe the solution you'd like**
No escape

**Comment by chrisbra** [comment]
You  really need to give more information, what are you trying to achieve, what you are seeing, etc. :/ 

My guess is you need a `:vim9` in front of the `:echo` for your command definition. Remember the command line by defaults does not support vim9 script syntax. 

Also, please consider asking vim usage questions on appropriate forums.

**Comment by yu3s** [comment]
I implemented an Rg command similar to fzf.vim, but after adding file completion, I need to manually escape `#` every time

If `#` is not followed by a number, can E195 be ignored?
such as `fzf#run`, `#include`

**Comment by chrisbra** [comment]
I don't follow (and you are still not giving enough information). What has file-completion have to do with `#` appearing on the command line? 

Please have a look at `:h fnameescape()`

**Comment by yu3s** [comment]
`#` As search content

For example, `Rg #include` requires the use of `Rg \# include`
I want to execute in the processing function
