### ISSUE TITLE
netrw plugin error on edd4ac3e8/v9.1.1056

### ISSUE THREAD

**Issue by jwbowen** [vim/vim#16541]
### Steps to reproduce

1. Compile edd4ac3e8 / v9.1.1056 and install
2. Launch vim from the command line
3. Observe error:
```
Error detected while processing /usr/local/share/vim/vim91/plugin/netrwPlugin.vim:
line    4:
netrw needs vim v9.1.1054
Press ENTER or type command to continue
```

### Expected behaviour

Vim launches cleanly

### Version of Vim

v9.1.1056

### Environment

Compiled on Ubuntu 24.04 with `--with-features=normal`, but from looking at the contents of `runtime/plugin/netrwPlugin.vim`, I don't know that the environment matters.

### Logs and stack traces

```shell

```

**Comment by gcanat** [comment]
Looks like some error in the logic. This should fix it:

```diff
diff --git a/runtime/plugin/netrwPlugin.vim b/runtime/plugin/netrwPlugin.vim
index f3684bb27..6c64ae048 100644
--- a/runtime/plugin/netrwPlugin.vim
+++ b/runtime/plugin/netrwPlugin.vim
@@ -1,6 +1,6 @@
 " Load the netrw package.

-if !has("patch-9.1.1054") || !has('nvim')
+if !has("patch-9.1.1054") && !has('nvim')
   echoerr 'netrw needs vim v9.1.1054'
   finish
 endif
```

**Comment by jwbowen** [comment]
Confirmed that it does!

**Comment by habamax** [comment]
I don't even load and use netrw and I still get this error:

```
# turn off netrw
g:loaded_netrw = 1
g:loaded_netrwPlugin = 1
```

Which doesn't look right.

**Comment by habamax** [comment]
Could you please also move this before anything else?

```
if &cp || exists("g:loaded_netrw") || exists("g:loaded_netrwPlugin")
  finish
endif
```

**Comment by chrisbra** [comment]
How about this one then:
```diff
diff --git a/runtime/pack/dist/opt/netrw/autoload/netrw.vim b/runtime/pack/dist/opt/netrw/autoload/netrw.vim
index 7d7ff15df..a57cfd23a 100644
--- a/runtime/pack/dist/opt/netrw/autoload/netrw.vim
+++ b/runtime/pack/dist/opt/netrw/autoload/netrw.vim
@@ -21,6 +21,12 @@ endif

 let g:loaded_netrw = "v176"

+if !has("patch-9.1.1054") && !has('nvim')
+  echoerr 'netrw needs Vim v9.1.1054'
+  finish
+endif
+
+
 let s:keepcpo= &cpo
 setl cpo&vim
 "DechoFuncName 1
diff --git a/runtime/plugin/netrwPlugin.vim b/runtime/plugin/netrwPlugin.vim
index f3684bb27..6d7a8660f 100644
--- a/runtime/plugin/netrwPlugin.vim
+++ b/runtime/plugin/netrwPlugin.vim
@@ -1,10 +1,5 @@
 " Load the netrw package.

-if !has("patch-9.1.1054") || !has('nvim')
-  echoerr 'netrw needs vim v9.1.1054'
-  finish
-endif
-
 if &cp || exists("g:loaded_netrw") || exists("g:loaded_netrwPlugin")
   finish
 endif
```

this moves the version check to the autoload file, so that it only throws an error once some functionality of the netrw plugin is actually being used.

CC @saccarosium

**Comment by jwbowen** [comment]
+1 for the "lazy" load approach.

I'm on 8297e2cee / v9.1.1057 without issue this morning.

**Comment by jwbowen** [comment]
+1 for the "lazy" load approach.

I'm on 8297e2cee / v9.1.1057 without issue this morning.

**Comment by cuantar** [comment]
Hooray :D  I saw this too, and thought to check for it here.  Already fixed, great!  best kind of bug.
