### ISSUE TITLE
There is a bug when deleting a whole python-buffer using `del b[:]`

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#1738]
```python
python << EOF

import vim
import time
with open("aaa.txt", 'r+') as f:
    aaa = f.readlines()

vim.command("vsp test.txt | setlocal ul=-1")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python << EOF

del b[:] # there is an issue here

vim.command("vsp test.txt")

start = time.time()
b[:] = aaa
print(time.time() - start)

EOF
endfunction

map <F5> :call Test()<CR>
```
source the code, then run test by pressing `<F5>` for several times, close the test.txt buffer window every time before pressing `<F5>`, you will find it takes longer and longer time to set the buffer with `b[:] = aaa`.
If `del b[:]` is removed, everything works well. I think there is a bug here.

Attachments:

- [issue.vim](https://github.com/Yggdroot/sample/blob/master/issue.vim)

- [aaa.txt](https://github.com/Yggdroot/sample/blob/master/aaa.txt)

**Comment by Yggdroot** [comment]
Find the root cause now. If `set foldmethod=manual`, everything goes well. If `&foldmethod == 'indent'`, there is the issue.
But I think this issue should not exist even though `&foldmethod == 'indent'`.

**Comment by lacygoill** [comment]
I cannot reproduce the issue with the Python3 interface.  Either the instructions to reproduce are incomplete, or the issue is specific to Python2, or the issue was fixed by a later patch.

[8.2.2271](https://github.com/vim/vim/releases/tag/v8.2.2271) has blocked the update of folds when Python changes a hidden buffer.  Since the current issue is related to folding, maybe it was fixed by this patch?

Can someone still reproduce?

**Comment by chrisbra** [comment]
Thanks. Can also not reproduce. Closing therefore

**Comment by Yggdroot** [comment]
I think this issue can not  be closed. It still exists.

vimrc

```vim
set nocp
set hidden
set fdm=indent
```

issue.vim
```vim
python3 << EOF

import vim
import time
with open("aaa.txt", 'r+') as f:
    aaa = f.readlines()
aaa = [line.rstrip("\r\n") for line in aaa]

vim.command("vsp test.txt | setlocal ul=-1")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python3 << EOF

del b[:] # there is an issue here

vim.command("vsp test.txt")

start = time.time()
b[:] = aaa
print(time.time() - start)

EOF
q
endfunction

map <F5> :call Test()<CR>
```

steps to reproduce:
1. vim -u vimrc issue.vim, aaa.txt is https://github.com/Yggdroot/sample/blob/master/aaa.txt
2. :so %
3. press `<F5>` for several times

I'm using  8.2.2282.

**Note**: This issue only happens when `&foldmethod == 'indent'`.

**Comment by lacygoill** [comment]
OK, now I can reproduce.  If I can find some time later, I'll see whether something can be simplified, either in `issue.vim` or in `aaa.txt`, and maybe get some profiling log.

I wonder whether it could be fixed in the same way #7598 was fixed; i.e. by temporarily blocking the folds update.

**Comment by chrisbra** [comment]
okay, so re-opening
