### ISSUE TITLE
undefined left shift in gethexchrs()

### ISSUE THREAD

**Issue by geeknik** [vim/vim#2255]
Triggered in `67435d9`, compiled with clang 6.0.0-trunk and `-fsanitize=address,undefined`.

./vim -u NONE -X -Z -e -s -c 'call search(getline("."))' -c ':qa!' test022

```regexp.c:3289:5: runtime error: left shift of 201326592 by 4 places cannot be represented in type 'int'
    #0 0xde43dd in gethexchrs /root/vim/src/regexp.c:3289:5
    #1 0xe4513b in nfa_regatom /root/vim/src/./regexp_nfa.c
    #2 0xe3b5b5 in nfa_regpiece /root/vim/src/./regexp_nfa.c:2055:11
    #3 0xe3b5b5 in nfa_regconcat /root/vim/src/./regexp_nfa.c:2296
    #4 0xe3ac67 in nfa_regbranch /root/vim/src/./regexp_nfa.c:2330:9
    #5 0xe3a114 in nfa_reg /root/vim/src/./regexp_nfa.c:2390:9
    #6 0xe2ff45 in re2post /root/vim/src/./regexp_nfa.c:2805:9
    #7 0xe2ff45 in nfa_regcomp /root/vim/src/./regexp_nfa.c:7257
    #8 0xdcc271 in vim_regcomp /root/vim/src/regexp.c:8153:16
    #9 0xf66486 in search_regcomp /root/vim/src/search.c:223:25
    #10 0xf69de2 in searchit /root/vim/src/search.c:621:9
    #11 0x70aec6 in search_cmn /root/vim/src/evalfunc.c:9363:17
    #12 0x6d83e1 in f_search /root/vim/src/evalfunc.c:9500:28
    #13 0x68b15b in call_internal_func /root/vim/src/evalfunc.c:1012:5
    #14 0x12341e6 in call_func /root/vim/src/userfunc.c:1446:14
    #15 0x1232b95 in get_func_tv /root/vim/src/userfunc.c:455:8
    #16 0x12575b6 in ex_call /root/vim/src/userfunc.c:3082:6
    #17 0x7d4058 in do_one_cmd /root/vim/src/ex_docmd.c:2908:2
    #18 0x7bc866 in do_cmdline /root/vim/src/ex_docmd.c:1071:17
    #19 0x13f138f in exe_commands /root/vim/src/main.c:2954:2
    #20 0x13f138f in vim_main2 /root/vim/src/main.c:799
    #21 0x13e5d3d in main /root/vim/src/main.c:415:12
    #22 0x7fa33af993f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #23 0x41bba9 in _start (/root/vim/src/vim+0x41bba9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior regexp.c:3289:5
```
[test022.gz](https://github.com/vim/vim/files/1418822/test022.gz)

**Comment by chrisbra** [comment]
I see [the problem](https://github.com/vim/vim/blob/master/src/regexp.c#L3284-L3292):
```c
 for (i = 0; i < maxinputlen; ++i)
    {
	c = regparse[0];
	if (!vim_isxdigit(c))
	    break;
	nr <<= 4;
	nr |= hex2nr(c);
	++regparse;
}
```
maxinputlen is 8. So it is doing a left shift of 4 positions 8 times. I think this should fix it:
```
diff --git a/src/regexp.c b/src/regexp.c
index 699a0bf9c..630a06da2 100644
--- a/src/regexp.c
+++ b/src/regexp.c
@@ -3277,9 +3277,9 @@ ungetchr(void)
     static int
 gethexchrs(int maxinputlen)
 {
-    int                nr = 0;
-    int                c;
-    int                i;
+    unsigned int       nr = 0;
+    int                        c;
+    int                        i;

     for (i = 0; i < maxinputlen; ++i)
     {
```

**Comment by chrisbra** [comment]
oh, that is not correct, I think all the callers also need to change their data types from int to long and this will lead to many fixes in many places ...

**Comment by brammool** [comment]
The essential part is to use an unsigned shift.  Truncation can still happen, but should not result in a runtime error.

I hate undefined behavior that the C standard introduced...
