### ISSUE TITLE
Netrw not working after upgrade

### ISSUE THREAD

**Issue by ghost** [vim/vim#2926]
netrw plugin stop working after upgrading to 8.1. 

`***sorry*** this version of netrw requires vim v7.4 with patch 213`

**Comment by brammool** [comment]
> netrw plugin stop working after upgrading to 8.1. 

That is weird, I don't see the commit that changed the version check...

-- 
ERIC IDLE PLAYED: THE DEAD COLLECTOR, MR BINT (A VILLAGE NE'ER-DO -WELL VERY
                  KEEN ON BURNING WITCHES), SIR ROBIN, THE GUARD WHO DOESN'T
                  HICOUGH BUT TRIES TO GET THINGS STRAIGHT, CONCORDE (SIR
                  LAUNCELOT'S TRUSTY STEED), ROGER THE SHRUBBER (A SHRUBBER),
                  BROTHER MAYNARD
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Fixed with 8.1.0001 (https://github.com/vim/vim/commit/00e45563384de01949b9c4df9155424604887b33).

**Comment by ghost** [comment]
It's weird, but it is not really fixed. Netrw still shows many errors that aren't present in v8.0.1850 e.g. you can't open a folder because it's says "Illegal file name", all additional tools that comes with netrw are also broken. Maybe it's netrw version error? Newest version of it works like a charm but after each open it duplicate it's view so we can have 10x the same file listed in explorer. ;)

**Comment by brammool** [comment]
> It's weird, but it is not really fixed. Netrw still shows many errors
> that aren't present in v8.0.1850 e.g. you can't open a folder because
> it's says "Illegal file name", all additional tools that comes with
> netrw are also broken. Maybe it's netrw version error? Newest version
> of it works like a charm but after each open it duplicate it's view so
> we can have 10x the same file listed in explorer. ;)

The netrw version included with 8.1 is unfortunately a very old one.
I tried including a newer version, but it failed my initial testing.

-- 
Every time I lose weight, it finds me again!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
