### ISSUE TITLE
$p appeares when opening a file

### ISSUE THREAD

**Issue by lylex** [vim/vim#3160]
When I open a file with vim, I found there always a '$p' appeares in the first line. I do not understand what it is for.

I am using 8.1.115.

**Comment by tonymec** [comment]
This problem was fixed in Vim 8.1.129.

**Comment by k-takata** [comment]
Related: #3083, #2008 

If you still have the problem after updating Vim to 8.1.129 or later, please let us know the following information:
* Which terminal emulator (and version) do you use?
* Result of `:echo v:termresponse`.
* Setting of `$TERM`.

**Comment by lylex** [comment]
@tonymec @k-takata Thanks for the quick response.
I have tried the latest 8.1.155, but still the same. And here is the information:

- terminal emulator: iTerm2 2.1.1
- Result of `:echo v:termresponse`: `^[[>0;95;c`
- $TERM: xterm-256color

**Comment by k-takata** [comment]
It looks the same case as https://github.com/vim/vim/issues/2008#issuecomment-396520207.
Your iTerm2 is old and not fully compatible with xterm. You should update iTerm2 or change the setting of $TERM. 

@brammool I still think that #2126 should be included, because quite a few people tend to set `$TERM` to "xterm" even if the terminal is not fully compatible with xterm.

**Comment by tonymec** [comment]
Yeah, we seem to have a recurrent problem with terminals pretending to be xterm and failing. Anything to eliminate the "false positives" (i.e. the not-really-compatibles) would be welcome. This iterm2 even pretends to be xterm patch 95, but its "third parameter" is absent rather than zero. FWIW, in a "real" xterm, and a reasonably modern one, I get `v:termresponse` = `^[[>41;330;0c` (I wonder what the 41 means — the help says it should be 0 for vt100 and 1 for vt220. Could it be because it is nearly maximized, with the Vim running in it seeing 202 columns x 72 lines?)

Best regards,
Tony.

**Comment by vim-ml** [comment]
On 2018-07-06, Tony Mechelynck wrote:
> Yeah, we seem to have a recurrent problem with terminals pretending to be xterm
> and failing. Anything to eliminate the "false positives" (i.e. the
> not-really-compatibles) would be welcome. This iterm2 even pretends to be xterm
> patch 95, but its "third parameter" is absent rather than zero. FWIW, in a
> "real" xterm, and a reasonably modern one, I get v:termresponse = ^[[>41;330;0c
> (I wonder what the 41 means — the help says it should be 0 for vt100 and 1 for
> vt220. Could it be because it is nearly maximized, with the Vim running in it
> seeing 202 columns x 72 lines?)

I have in my notes that 41 means the terminal type is VT420, but my
notes don't include a citation.  I did find a couple of places in
the xterm 318 source code where "41" is paired with a comment about
VT420.

My xterm 318 includes the 41 whether it is maximized or just 80x24.

Regards,
Gary

**Comment by brammool** [comment]
> @tonymec @k-takata Thanks for the quick response.
> I have tried the latest 8.1.155, and here is the information:
> 
> - terminal emulator: iTerm2 2.1.1
> - Result of `:echo v:termresponse`: `^[[>0;95;c`
> - $TERM: xterm-256color

Hmm, we recognize >0;95;0c as iTerm2.  I suppose we should recognize
>0;95;c as an old iTerm2.

I haven't tried the "generic solution" yet and checked whether it would
introduce new problems.

-- 
hundred-and-one symptoms of being an internet addict:
195. Your cat has its own home page.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Fixed by 8.1.0157: https://github.com/vim/vim/commit/e330ef42f256e60017e5f8bf4be79a5308fe9e2f
