### ISSUE TITLE
warning undefined reference to `_PyObject_DebugFree' when compiling on Ubuntu 18

### ISSUE THREAD

**Issue by dmmfll** [vim/vim#3499]
In the past, I have successfully compiled vim on Ubuntu 14 that has Python version 3.4 installed by default.  Following the instructions in src/INSTALL, I executed the following commands and the code compiled and vim was installed without errors. Python3 functions normally inside of vim.

```
make
make install
```

I recently changed to a new box with Ubuntu 18  that has Python version 3.6.4 installed by default.

When I run the above commands, I get the following error:

```
if_python3.c: In function ‘call_PyObject_Free’:
if_python3.c:757:5: warning: implicit declaration of function ‘_PyObject_DebugFree’; did you mean ‘PyObject_Free’? [-Wimplicit-function-declaration]
     _PyObject_DebugFree(p);
```

vim does not install because of this warning.

I changed line 757 in if_python3.c by substituting `_PyObject_DebugFree` with `PyObject_Free`. 

(This was a total guess. I know little to nothing about C or what the consequences of the substitution might be.) 

The code compiles and installs vim after running

```
make
make install
```

The output of  `ldd /usr/local/bin/vim`:

```
libpython3.6dm.so.1.0 => /usr/local/lib/libpython3.6dm.so.1.0 (0x00007f0e65eaa000)
```

(I compiled that Python3.6.6 from cpython source.)

So far vim compiled from tag v8.1.0438 is functioning as expected on the Ubuntu 18 box with the edit I made in if_python3.c

**Comment by dmmfll** [comment]
Fixed in v8.1.0443.

**Comment by davidwincent** [comment]
I am still getting this error when building from latest master

`./configure         --with-features=huge \
            --enable-multibyte \
            --enable-python3interp \
            --with-python3-config-dir=/usr/local/lib/python3.5/config-3.5dm \
            --enable-gui=gtk2 --enable-cscope`

`make`

Gives =>
```
if_python3.c: In function ‘call_PyObject_Free’:
if_python3.c:755:5: warning: implicit declaration of function ‘_PyObject_DebugFree’ [-Wimplicit-function-declaration]
     _PyObject_DebugFree(p);
     ^
```

Os version: Ubuntu 16.04.5 LTS
Python version: 3.5.6

**Comment by davidwincent** [comment]
It works if I rebuild python from source without `--with-pydebug` and change `--with-python3-config-dir` in vim configure

`sudo make distclean`

`./configure         --with-features=huge \
            --enable-multibyte \
            --enable-python3interp \
            --with-python3-config-dir=/usr/local/lib/python3.5/config-3.5m \
            --enable-gui=gtk2 --enable-cscope`

`make`
`make test`
Gives =>
```
make -f Makefile vim
make[1]: Entering directory '/usr/src/vim/src'
make[1]: 'vim' is up to date.
make[1]: Leaving directory '/usr/src/vim/src'
```
