### ISSUE TITLE
Gvim Font-glitches for combining characters (pango-view has no problems) in "Ubuntu Mono" font

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#393]
```
What steps will reproduce the problem?
1.
Consider a text file with one line:
----á----
i.e. between the "minus signs": U+0061 U+0301 (g8: 61 + cc 81)
2. gvim -u NONE -U NONE -N  -c 'set gfn=Ubuntu\ Mono\ 30'

What is the expected output? What do you see instead?
The expected output: the same es the output of 
pango-view -t "----á-----" --font="Ubuntu mono 65"
There is a screen-shot attached with the output of Gvim and the expected output 
(of pango-view).

This problem does not occur with e.g.
se gfn=Bitstream\ Vera\ Sans\ Mono\ Bold\ 12

What version of the product are you using? On what operating system?
Gvim 7.4.826 on Fedora 22

Please provide any additional information below.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 14 2015 13:47:52)
Included patches: 1-207, 209-826
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             -ebcdic          +localmap        +printer         +title
+arabic          +emacs_tags      -lua             +profile         +toolbar
+autocmd         +eval            +menu            +python/dyn      
+user_commands
+balloon_eval    +ex_extra        +mksession       -python3         +vertsplit
+browse          +extra_search    +modify_fname    +quickfix        +virtualedit
++builtin_terms  +farsi           +mouse           +reltime         +visual
+byte_offset     +file_in_path    +mouseshape      +rightleft       +visualextra
+cindent         +find_in_path    +mouse_dec       +ruby/dyn        +viminfo
+clientserver    +float           +mouse_gpm       +scrollbind      +vreplace
+clipboard       +folding         -mouse_jsbterm   +signs           +wildignore
+cmdline_compl   -footer          +mouse_netterm   +smartindent     +wildmenu
+cmdline_hist    +fork()          +mouse_sgr       -sniff           +windows
+cmdline_info    +gettext         -mouse_sysmouse  +startuptime     +writebackup
+comments        -hangul_input    +mouse_urxvt     +statusline      +X11
+conceal         +iconv           +mouse_xterm     -sun_workshop    -xfontset
+cryptv          +insert_expand   +multi_byte      +syntax          +xim
+cscope          +jumplist        +multi_lang      +tag_binary      
+xsmp_interact
+cursorbind      +keymap          -mzscheme        +tag_old_static  
+xterm_clipboard
+cursorshape     +langmap         +netbeans_intg   -tag_any_white   -xterm_save
+dialog_con_gui  +libcall         +path_extra      -tcl             +xpm
+diff            +linebreak       +perl            +terminfo        
+digraphs        +lispindent      +persistent_undo +termresponse    
+dnd             +listcmds        +postscript      +textobjects     
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread 
-I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 
-I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 
-I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 
-I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 
-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 
-I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16    -O2 
-g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong 
--param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic 
-D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
 
Linking: gcc   -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic 
-Wl,--enable-new-dtags  -Wl,-z,relro  -L/usr/local/lib -Wl,--as-needed -o vim   
-lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 
-lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig 
-lfreetype  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -lnsl  -lselinux  
-lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags  -fstack-protector 
-L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm 
-lcrypt -lutil -lpthread -lc        

```

Original issue reported on code.google.com by `Ludwi...@gmx.de` on 16 Aug 2015 at 7:29

Attachments:
* [GvimUbuntuFontProblem.png](https://storage.googleapis.com/google-code-attachments/vim/issue-393/comment-0/GvimUbuntuFontProblem.png)

**Comment by chrisbra** [comment]
Could you attach the picture again? (this is a small test)

**Comment by chrisbra** [comment]
Could you attach the picture again? (this is a small test)

**Comment by 2vek** [comment]
Just reproduced this problem, doing as described in bug report.

on gnome terminal using Ubuntu Mono looks fine
![screenshot from 2015-08-21 18-45-50](https://cloud.githubusercontent.com/assets/2778313/9409060/27d699ae-4835-11e5-9a80-c2489f7053e3.png)
on gvim, you can see weird artifacts around `á`
![screenshot from 2015-08-21 18-44-21](https://cloud.githubusercontent.com/assets/2778313/9409063/29f5f748-4835-11e5-873f-7f43eafd0e36.png)
Using Bitstream Vera Sans Mono on gvim works fine
![screenshot from 2015-08-21 18-54-32](https://cloud.githubusercontent.com/assets/2778313/9409196/32c5e40e-4836-11e5-9e8f-e3ac4ba042a9.png)

Also, few months ago I filed a issue(https://github.com/tonsky/FiraCode/issues/20) about font glitch with gvim. I think these two issue are related.

**Comment by vim-ml** [comment]
This is probably some  gtk issue

**Comment by vim-ml** [comment]
(this is a a test)

**Comment by 2vek** [comment]
> This is probably some gtk issue

Are you sure? I tested the _same_ text with `gedit`(gtk3 app) and `mousepad`(gtk2 app) using the three mentioned fonts and I don't see any text rendering issue with them.

**Comment by luchr** [comment]
This happens if you want "pango" to draw a combining Unicode codepoint without preceeding codepoint (in some fonts).
Here is a complete example to trigger this behaviour:
https://gist.github.com/luchr/fdd435b7e2c9acf4b650
![test1](https://cloud.githubusercontent.com/assets/7441996/9632537/3db95e80-5188-11e5-90eb-9a8afe7d829f.png)
It seems gvim is instructing pango to draw each codepoint seperately.

**Comment by luchr** [comment]
Use `pango_shape_full` instead of `pango_shape` to give pango a chance to see the _context_ and to see, if there is a preceding code point. 

Using `pango_shape_full` fixes this problem for me.

```
 --- vim74/src/gui_gtk_x11.c.orig   2015-09-07 16:19:44.054802201 +0200
 +++ vim74/src/gui_gtk_x11.c    2015-09-07 16:20:05.803460620 +0200
 @@ -5063,8 +5063,8 @@
         * done, because drawing the cursor would change the display. */
        item->analysis.shape_engine = default_shape_engine;

 -      pango_shape((const char *)s + item->offset, item->length,
 -          &item->analysis, glyphs);
 +      pango_shape_full((const char *)s + item->offset, item->length,
 +               (const char *)s, len, &item->analysis, glyphs);
        /*
         * Fixed-width hack: iterate over the array and assign a fixed
         * width to each glyph, thus overriding the choice made by the
```

**Comment by chrisbra** [comment]
fixed by 7.4.855

**Comment by barraponto** [comment]
@chrisbra I still see this issue, running gVim 7.4.1910 under Arch Linux.

Some package versions:

gtk2 2.24.30+95+g876b5f7-1
gtk3 3.20.6-1
pango 1.40.1-1
cairo-infinality-ultimate 1.14.6-2
