### ISSUE TITLE
windows gvim v8.1.1002 crashes sometimes when use gtags ctrl+]

### ISSUE THREAD

**Issue by general0000** [vim/vim#4102]
1、I use gtags ctrl+] to jump to some function, which has multiple definitions, gvim crashes after entering selected  number.
2、Stack backtrace：
>	gvim.exe!screen_puts_len(unsigned char * text, int textlen, int row, int col, int attr) line 7488	C
 	gvim.exe!t_puts(int * t_col, unsigned char * t_s, unsigned char * s, int attr) line 2538	C
 	gvim.exe!msg_puts_display(unsigned char * str, int maxlen, int attr, int recurse) line 2230	C
 	gvim.exe!msg_puts_attr_len(char * str, int maxlen, int attr) line 2019	C
 	gvim.exe!msg_outtrans_len_attr(unsigned char * msgstr, int len, int attr) line 1555	C
 	gvim.exe!msg_attr_keep(char * s, int attr, int keep) line 183	C
 	gvim.exe!msg_trunc_attr(char * s, int force, int attr) line 830	C
 	gvim.exe!readfile(unsigned char * fname, unsigned char * sfname, long from, long lines_to_skip, long lines_to_read, exarg * eap, int flags) line 2522	C
 	gvim.exe!open_buffer(int read_stdin, exarg * eap, int flags) line 231	C
 	gvim.exe!do_ecmd(int fnum, unsigned char * ffname, unsigned char * sfname, exarg * eap, long newlnum, int flags, window_S * oldwin) line 4260	C
 	gvim.exe!getfile(int fnum, unsigned char * ffname_arg, unsigned char * setpm, int lnum, long forceit, int) line 3723	C
 	gvim.exe!jumpto_tag(unsigned char * lbuf_arg, int forceit, int keep_help) line 3264	C
 	gvim.exe!do_tag(unsigned char * tag, int type, int count, int forceit, int verbose) line 1029	C
 	gvim.exe!cs_find_common(char * opt, char * pat, int forceit, int verbose, int use_ll, unsigned char * cmdline) line 1270	C
 	gvim.exe!ex_cstag(exarg * eap) line 266	C
 	gvim.exe!ex_tag_cmd(exarg * eap, unsigned char * name) line 10684	C
 	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2526	C
 	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 1038	C
 	gvim.exe!nv_ident(cmdarg_S * cap) line 5734	C
 	gvim.exe!normal_cmd(oparg_S * oap, int toplevel) line 1108	C
 	gvim.exe!main_loop(int cmdwin, int noexmode) line 1362	C
 	gvim.exe!vim_main2() line 906	C
 	gvim.exe!VimMain(int argc, char * * argv) line 443	C
 	gvim.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInst, char * lpszCmdLine, int nCmdShow) line 130	C
3、The crash context:
    screen.c:
	off = 2281701376
	int row = -1

**Comment by chrisbra** [comment]
any way to reproduce this? Can you check, what row and col are in that case? possibly invalid for some reason?

**Comment by general0000** [comment]
> any way to reproduce this? Can you check, what row and col are in that case? possibly invalid for some reason?

1、Yes,  sometimes I can reproduce it.  The row is -1, and the col is 0,  and :
    off = LineOffset[row] + col;   // off is 2281701376，   in function： screen_puts_len 

2、There is safety check in screen_puts_len function
    void screen_puts_len（
    {   ....
        if (ScreenLines == NULL || row >= screen_Rows)	/* safety check */
	    return;
        off = LineOffset[row] + col;
       ...
    }

But the safety check is incomplete. Maybe it should be:
       if (ScreenLines == NULL || row >= screen_Rows  ||  row <0 )
or:
      if (ScreenLines == NULL ||  (unsigned)row >= screen_Rows)

But, I can't understand why produce -1 row.

**Comment by general0000** [comment]
This crash is really annoying.  Can you pull this request, please ? @chrisbra , thanks.

**Comment by chrisbra** [comment]
so this patch should at least fix the segfault, right? (I suppose col shouldn't be negative as well, right?)

ping @brammool 

```patch
diff --git a/src/screen.c b/src/screen.c
index 37999bbf6..08ef08331 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -7707,7 +7707,8 @@ screen_puts_len(
     int                force_redraw_next = FALSE;
     int                need_redraw;

-    if (ScreenLines == NULL || row >= screen_Rows)     /* safety check */
+    // safety check
+    if (ScreenLines == NULL || row >= screen_Rows || row < 0 || col < 0)
        return;
     off = LineOffset[row] + col;

```

would still be interesting to know, how row can be `-1`. Can you add a watch on `msg_row` to break when it becomes less than zero and see where this happens? Or some way to reliably reproduce this?

**Comment by chrisbra** [comment]
crash should be fixed as of 8.1.1458. Please try to figure out, what makes msg_row negative. Thanks.

**Comment by general0000** [comment]
> crash should be fixed as of 8.1.1458. Please try to figure out, what makes msg_row negative. Thanks.

1、Sorry， @chrisbra ,  the segfault still exists,  because msg_row is used in many functions.  Now crash is here  when msg_clr_eos_force calls screen_fill(msg_row...) :
```
      void  screen_fill(
    int	    start_row,     //// msg_row is -1， msg_clr_eos_force calls screen_fill(msg_row, )
   ...
    )
{
   ...
    for (row = start_row; row < end_row; ++row)
    {     ...
            off = LineOffset[row] + col;
	    end_off = LineOffset[row] + end_col;
	    /* skip blanks (used often, keep it fast!) */
	    if (enc_utf8)
		while (off < end_off && ScreenLines[off] == ' '
			  && ScreenAttrs[off] == 0 && ScreenLinesUC[off] == 0)
		    ++off;
```

2、But I have found the cause of the problem:
the msg_row with -1 value comes from here:
```
    void
msg_start(void)
{
    if (!msg_scroll && full_screen)	/* overwrite last message */
    {
	msg_row = cmdline_row;     ////  here cmdline_row is -1 
```
the cmdline_row with -1 comes from here:
```
    int
prompt_for_number(int *mouse_used)
{
    int		i;
    int		save_cmdline_row;
    int		save_State;
    ...
    // Set the state such that text can be selected/copied/pasted and we still
    // get mouse events. redraw_after_callback() will not redraw if cmdline_row
    // is zero.
    save_cmdline_row = cmdline_row;
    cmdline_row = 0;
    save_State = State;
    State = CMDLINE;
#ifdef FEAT_MOUSE
    // May show different mouse shape.
    setmouse();
#endif

   //// when wait for input, enter inchar_loop() to process messages and mess msg_row up!
    i = get_number(TRUE, mouse_used);   
    if (KeyTyped)
    {
	/* don't call wait_return() now */
	/* msg_putchar('\n'); */
	cmdline_row = msg_row - 1;      ////  here msg_row is 0  !!!!!
```

When pressing ctrl+] to jump to some tag with multiple definitions,  the prompt_for_number function is called, and at the begining of prompt_for_number msg_row is positive.  When run into get_number to wait for input,  inchar_loop() begins to process messages and mess msg_row up, 
as follows:

         >	gvim.exe!msg_start() line 1330	C          //// here msg_row is changed to 0
          	gvim.exe!msg_attr_keep(char * s, int attr, int keep) line 176	C
          	gvim.exe!do_doautocmd(unsigned char * arg, int do_msg, int * did_something) line 1318	C
          	gvim.exe!ex_doautocmd(exarg * eap) line 5441	C
          	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2500	C
          	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 999	C
          	gvim.exe!call_user_func(ufunc_T * fp, int argcount, typval_T * argvars, typval_T * rettv, long firstline, long lastline, dictvar_S * selfdict) line 1069	C
          	gvim.exe!call_func(unsigned char * funcname, int len, typval_T * rettv, int argcount_in, typval_T * argvars_in, int (int, typval_T *, int) * argv_func, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict_in) line 1628	C
          	gvim.exe!get_func_tv(unsigned char * name, int len, typval_T * rettv, unsigned char * * arg, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict) line 490	C
          	gvim.exe!ex_call(exarg * eap) line 3344	C
          	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2500	C
          	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 999	C
          	gvim.exe!call_user_func(ufunc_T * fp, int argcount, typval_T * argvars, typval_T * rettv, long firstline, long lastline, dictvar_S * selfdict) line 1069	C
          	gvim.exe!call_func(unsigned char * funcname, int len, typval_T * rettv, int argcount_in, typval_T * argvars_in, int (int, typval_T *, int) * argv_func, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict_in) line 1628	C
          	gvim.exe!get_func_tv(unsigned char * name, int len, typval_T * rettv, unsigned char * * arg, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict) line 490	C
          	gvim.exe!ex_call(exarg * eap) line 3344	C
          	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2500	C
          	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 999	C
          	gvim.exe!call_user_func(ufunc_T * fp, int argcount, typval_T * argvars, typval_T * rettv, long firstline, long lastline, dictvar_S * selfdict) line 1069	C
          	gvim.exe!call_func(unsigned char * funcname, int len, typval_T * rettv, int argcount_in, typval_T * argvars_in, int (int, typval_T *, int) * argv_func, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict_in) line 1628	C
          	gvim.exe!get_func_tv(unsigned char * name, int len, typval_T * rettv, unsigned char * * arg, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict) line 490	C
          	gvim.exe!handle_subscript(unsigned char * * arg, typval_T * rettv, int evaluate, int verbose) line 7240	C
          	gvim.exe!ex_call(exarg * eap) line 3353	C
          	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2500	C
          	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 999	C
          	gvim.exe!call_user_func(ufunc_T * fp, int argcount, typval_T * argvars, typval_T * rettv, long firstline, long lastline, dictvar_S * selfdict) line 1069	C
          	gvim.exe!call_func(unsigned char * funcname, int len, typval_T * rettv, int argcount_in, typval_T * argvars_in, int (int, typval_T *, int) * argv_func, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict_in) line 1628	C
          	gvim.exe!job_cleanup(jobvar_S * job) line 5479	C
          	gvim.exe!f_job_status(typval_T * argvars, typval_T * rettv) line 7793	C
          	gvim.exe!call_internal_func(unsigned char * name, int argcount, typval_T * argvars, typval_T * rettv) line 1175	C
          	gvim.exe!call_func(unsigned char * funcname, int len, typval_T * rettv, int argcount_in, typval_T * argvars_in, int (int, typval_T *, int) * argv_func, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict_in) line 1644	C
          	gvim.exe!get_func_tv(unsigned char * name, int len, typval_T * rettv, unsigned char * * arg, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict) line 490	C
          	gvim.exe!eval7(unsigned char * * arg, typval_T * rettv, int evaluate, int want_string) line 4578	C
          	gvim.exe!eval6(unsigned char * * arg, typval_T * rettv, int evaluate, int want_string) line 4173	C
          	gvim.exe!eval5(unsigned char * * arg, typval_T * rettv, int evaluate) line 3964	C
          	gvim.exe!eval4(unsigned char * * arg, typval_T * rettv, int evaluate) line 3846	C
          	gvim.exe!eval3(unsigned char * * arg, typval_T * rettv, int evaluate) line 3766	C
          	gvim.exe!eval2(unsigned char * * arg, typval_T * rettv, int evaluate) line 3698	C
          	gvim.exe!eval1(unsigned char * * arg, typval_T * rettv, int evaluate) line 3626	C
          	gvim.exe!eval0(unsigned char * arg, typval_T * rettv, unsigned char * * nextcmd, int evaluate) line 3584	C
          	gvim.exe!eval_to_bool(unsigned char * arg, int * error, unsigned char * * nextcmd, int skip) line 714	C
          	gvim.exe!ex_if(exarg * eap) line 898	C
          	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2500	C
          	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 999	C
          	gvim.exe!call_user_func(ufunc_T * fp, int argcount, typval_T * argvars, typval_T * rettv, long firstline, long lastline, dictvar_S * selfdict) line 1069	C
          	gvim.exe!call_func(unsigned char * funcname, int len, typval_T * rettv, int argcount_in, typval_T * argvars_in, int (int, typval_T *, int) * argv_func, long firstline, long lastline, int * doesrange, int evaluate, partial_S * partial, dictvar_S * selfdict_in) line 1628	C
          	gvim.exe!channel_close(channel_S * channel, int invoke_close_cb) line 2973	C
          	gvim.exe!channel_parse_messages() line 4318	C
          	gvim.exe!parse_queued_messages() line 4476	C
          	gvim.exe!inchar_loop(unsigned char * buf, int maxlen, long wtime, int tb_change_cnt, int (long, int *, int) *) line 299	C
          	gvim.exe!gui_wait_for_chars_buf(unsigned char * buf, int maxlen, long wtime, int tb_change_cnt) line 2994	C
          	gvim.exe!ui_inchar(unsigned char * buf, int maxlen, long wtime, int tb_change_cnt) line 225	C
          	gvim.exe!inchar(unsigned char * buf, int maxlen, long wait_time) line 3092	C
          	gvim.exe!vgetorpeek(int advance) line 2870	C
          	gvim.exe!vgetc() line 1602	C
          	gvim.exe!get_number(int colon, int * mouse_used) line 1376	C
          	gvim.exe!prompt_for_number(int * mouse_used) line 1448	C
          	gvim.exe!do_tag(unsigned char * tag, int type, int count, int forceit, int verbose) line 644	C
          	gvim.exe!cs_find_common(char * opt, char * pat, int forceit, int verbose, int use_ll, unsigned char * cmdline) line 1270	C
          	gvim.exe!ex_cstag(exarg * eap) line 266	C
          	gvim.exe!ex_tag_cmd(exarg * eap, unsigned char * name) line 9195	C
          	gvim.exe!do_one_cmd(unsigned char * * cmdlinep, int sourcing, condstack * cstack, unsigned char * (int, void *, int) * fgetline, void * cookie) line 2500	C
          	gvim.exe!do_cmdline(unsigned char * cmdline, unsigned char * (int, void *, int) * fgetline, void * cookie, int flags) line 999	C
          	gvim.exe!nv_ident(cmdarg_S * cap) line 5727	C
          	gvim.exe!normal_cmd(oparg_S * oap, int toplevel) line 1100	C
          	gvim.exe!main_loop(int cmdwin, int noexmode) line 1373	C
          	gvim.exe!vim_main2() line 908	C
          	gvim.exe!VimMain(int) line 446	C
          	gvim.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInst, wchar_t * lpszCmdLine, int nCmdShow) line 49	C

**Comment by general0000** [comment]
To prevent from this segfault ,  I think :  
    1、msg_row need be saved before calling get_number();
    2、Subtractions could easily lead to overflow， safety check is necessary；
Refer to change1 and change2,  as follows：
```c
    int
prompt_for_number(int *mouse_used)
{
    int		i;
    int		save_cmdline_row;
    int		save_State;
    int                save_msg_row = msg_row;   //////////// change 1, 

    /* When using ":silent" assume that <CR> was entered. */
    if (mouse_used != NULL)
	msg_puts(_("Type number and <Enter> or click with mouse (empty cancels): "));
    else
	msg_puts(_("Type number and <Enter> (empty cancels): "));

    // Set the state such that text can be selected/copied/pasted and we still
    // get mouse events. redraw_after_callback() will not redraw if cmdline_row
    // is zero.
    save_cmdline_row = cmdline_row;
    cmdline_row = 0;
    save_State = State;
    State = CMDLINE;
#ifdef FEAT_MOUSE
    // May show different mouse shape.
    setmouse();
#endif

    i = get_number(TRUE, mouse_used);
    if (KeyTyped)
    {
	/* don't call wait_return() now */
	/* msg_putchar('\n'); */
	cmdline_row = msg_row - 1;  //////////// change 2, change to:  cmdline_row = (save_msg_row > 0 ? save_msg_row - 1 : 0);
	need_wait_return = FALSE;
	msg_didany = FALSE;
	msg_didout = FALSE;
    }
    else
	cmdline_row = save_cmdline_row;
    State = save_State;
#ifdef FEAT_MOUSE
    // May need to restore mouse shape.
    setmouse();
#endif

    return i;
}
```
Is that appropriate ?   @chrisbra

**Comment by brammool** [comment]
> > crash should be fixed as of 8.1.1458. Please try to figure out, what makes msg_row negative. Thanks.
> 
> 1、Sorry， @chrisbra ,  the segfault still exists,  because msg_row is
> used in many functions.  Now crash is here  when msg_clr_eos_force
> calls screen_fill(msg_row...) :
>       `    void  screen_fill(
>     int	    start_row,     //// msg_row is -1， msg_clr_eos_force calls screen_fill(msg_row, ...
>    ......)
> {
>   ......
>     for (row = start_row; row < end_row; ++row)
>     {
> ......
>             off = LineOffset[row] + col;
> 	    end_off = LineOffset[row] + end_col;
> 	    /* skip blanks (used often, keep it fast!) */
> 	    if (enc_utf8)
> 		while (off < end_off && ScreenLines[off] == ' '
> 			  && ScreenAttrs[off] == 0 && ScreenLinesUC[off] == 0)
> 		    ++off;`
> 
> 2、But I have found the cause of the problem:
> the msg_row with -1 value comes from here:
> `    void
> msg_start(void)
> {
>     ...
>     if (!msg_scroll && full_screen)	/* overwrite last message */
>     {
> 	msg_row = cmdline_row;     ////  here cmdline_row is -1
> `    
> 
> the cmdline_row with -1 comes from here:
> `    int
> prompt_for_number(int *mouse_used)
> {
>     int		i;
>     int		save_cmdline_row;
>     int		save_State;
> 
>    ......
>     // Set the state such that text can be selected/copied/pasted and we still
>     // get mouse events. redraw_after_callback() will not redraw if cmdline_row
>     // is zero.
>     save_cmdline_row = cmdline_row;
>     cmdline_row = 0;
>     save_State = State;
>     State = CMDLINE;
> #ifdef FEAT_MOUSE
>     // May show different mouse shape.
>     setmouse();
> #endif
> 
>     i = get_number(TRUE, mouse_used);   //// when wait for input, enter inchar_loop() to process messages and mess msg_row up!
>     if (KeyTyped)
>     {
> 	/* don't call wait_return() now */
> 	/* msg_putchar('\n'); */
> 	cmdline_row = msg_row - 1;      ////  here msg_row is 0  !!!!!
> `
> When pressing ctrl+] to jump to some tag with multiple definitions,  the prompt_for_number function is called, and at the begining of prompt_for_number msg_row is positive.  When run into get_number to wait for input,  inchar_loop() begins to process messages and mess msg_row up, as follows:
>          >	gvim.exe!msg_start() line 1330	C          //// here msg_row is changed to 0

Thank you very much for spending time on this.  Thus the proper fix is
to check msg_row before subtracting from it.

I would like to make a test for this, but it's unclear to me how inside
inchar_loop() msg_start() is called.  What triggers this?  Is there some
callback that outputs a message perhaps?

-- 
hundred-and-one symptoms of being an internet addict:
133. You communicate with people on other continents more than you
     do with your own neighbors.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by general0000** [comment]
> > crash should be fixed as of 8.1.1458. Please try to figure out, what makes msg_row negative. Thanks. 1、Sorry， @chrisbra , the segfault still exists, because msg_row is used in many functions. Now crash is here when msg_clr_eos_force calls screen_fill(msg_row...) : ` void screen_fill( int	start_row, //// msg_row is -1， msg_clr_eos_force calls screen_fill(msg_row, ... ......) { ...... for (row = start_row; row < end_row; ++row) { ...... off = LineOffset[row] + col; end_off = LineOffset[row] + end_col; /* skip blanks (used often, keep it fast!) */ if (enc_utf8) while (off < end_off && ScreenLines[off] == ' ' && ScreenAttrs[off] == 0 && ScreenLinesUC[off] == 0) ++off;` 2、But I have found the cause of the problem: the msg_row with -1 value comes from here: ` void msg_start(void) { ... if (!msg_scroll && full_screen)	/* overwrite last message */ { msg_row = cmdline_row; //// here cmdline_row is -1 ` the cmdline_row with -1 comes from here: ` int prompt_for_number(int *mouse_used) { int	i; int	save_cmdline_row; int	save_State; ...... // Set the state such that text can be selected/copied/pasted and we still // get mouse events. redraw_after_callback() will not redraw if cmdline_row // is zero. save_cmdline_row = cmdline_row; cmdline_row = 0; save_State = State; State = CMDLINE; #ifdef FEAT_MOUSE // May show different mouse shape. setmouse(); #endif i = get_number(TRUE, mouse_used); //// when wait for input, enter inchar_loop() to process messages and mess msg_row up! if (KeyTyped) { /* don't call wait_return() now */ /* msg_putchar('\n'); */ cmdline_row = msg_row - 1; //// here msg_row is 0 !!!!! ` When pressing ctrl+] to jump to some tag with multiple definitions, the prompt_for_number function is called, and at the begining of prompt_for_number msg_row is positive. When run into get_number to wait for input, inchar_loop() begins to process messages and mess msg_row up, as follows: >	gvim.exe!msg_start() line 1330	C //// here msg_row is changed to 0
> Thank you very much for spending time on this. Thus the proper fix is to check msg_row before subtracting from it. I would like to make a test for this, but it's unclear to me how inside inchar_loop() msg_start() is called. What triggers this? Is there some callback that outputs a message perhaps?
> […](#)
> -- hundred-and-one symptoms of being an internet addict: 133. You communicate with people on other continents more than you do with your own neighbors. /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\\ /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\ \\\ an exciting new programming language -- http://www.Zimbu.org /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

Now I can reproduce stably.  It involves two plugins:  easymotion and ALE:
1、I use easymotion to jump to one tag with multiple definitions;
2、Easymotion triggers TextChanged event;
3、TextChanged event triggers ALE to refresh asynchronous with delay;
4、It is ALE's callback that outputs lint result;
@brammool

**Comment by brammool** [comment]
> > Thank you very much for spending time on this. Thus the proper fix
> > is to check msg_row before subtracting from it. I would like to make
> > a test for this, but it's unclear to me how inside inchar_loop()
> > msg_start() is called. What triggers this? Is there some callback
> > that outputs a message perhaps?
> > […](#)
> 
> Now I can reproduce stably.  It involves two plugins:  easymotion and ALE:
> 1、I use easymotion to jump to one tag with multiple definitions;
> 2、Easymotion triggers TextChanged event;
> 3、TextChanged event triggers ALE to refresh asynchronous with delay;
> 4、It is ALE's callback that outputs lint result;

Have you tried with patch 8.1.1509?

-- 
hundred-and-one symptoms of being an internet addict:
142. You dream about creating the world's greatest web site.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by general0000** [comment]
> > Thank you very much for spending time on this. Thus the proper fix > is to check msg_row before subtracting from it. I would like to make > a test for this, but it's unclear to me how inside inchar_loop() > msg_start() is called. What triggers this? Is there some callback > that outputs a message perhaps? > […](#) Now I can reproduce stably. It involves two plugins: easymotion and ALE: 1、I use easymotion to jump to one tag with multiple definitions; 2、Easymotion triggers TextChanged event; 3、TextChanged event triggers ALE to refresh asynchronous with delay; 4、It is ALE's callback that outputs lint result;
> Have you tried with patch 8.1.1509?
> […](#)
> -- hundred-and-one symptoms of being an internet addict: 142. You dream about creating the world's greatest web site. /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\\ /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\ \\\ an exciting new programming language -- http://www.Zimbu.org /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

Now I use patch 8.1.1512.  It works well.  Thanks.
