### ISSUE TITLE
:bnext doesn't behave properly (and hasn't for many versions, probably)

### ISSUE THREAD

**Issue by SenileFelineS** [vim/vim#4478]
**Description**
According to the documentation for :bnext (at [vimhelp.org](https://vimhelp.org/windows.txt.html#:bnext)), if you have multiple help buffers, you **should** be able to use :bnext to move *exclusively* to the next help buffer, and skip over any normal buffers (and probably other kinds of buffers).

*This doesn't happen*

Instead, you're sent to the next normal buffer (or perhaps another type of buffer --haven't checked), if available. If there are no normal buffers and only help buffers, the error ```E85 : There is no listed buffer``` is thrown.

**Expected behavior**
:bn (or :bnext) should move the user from the current help buffer to the next available help buffer, and skip over any normal buffers.

**Environment:**
 - Vim versions tested: 7.3, 7.4, and 8.1
 - OS: macOS 10.7
 - Terminal: Terminal.app, MacVim.app

<sub>Apparently almost no one has multiple help buffers open but me...</sub>

**Comment by brammool** [comment]
> **Description**
> According to the documentation for :bnext (at [vimhelp.org](https://vimhelp.org/windows.txt.html#:bnext)), if you have multiple help buffers, you **should** be able to use :bnext to move *exclusively* to the next help buffer, and skip over any normal buffers (and probably other kinds of buffers).
> 
> *This doesn't happen*
> 
> Instead, you're sent to the next normal buffer (or perhaps another type of buffer --haven't checked), if available. If there are no normal buffers and only help buffers, the error ```E85 : There is no listed buffer``` is thrown.
> 
> 
> 
> **Expected behavior**
> :bn (or :bnext) should move the user from the current help buffer to the next available help buffer, and skip over any normal buffers.
> 
> **Environment:**
>  - Vim versions tested: 7.3, 7.4, and 8.1
>  - OS: macOS 10.7
>  - Terminal: Terminal.app, MacVim.app
> 
> <sub>Apparently almost no one has multiple help buffers open but me...</sub>

Yeah, using :bnext in a help buffer doesn't work as documented.  I think
we should fix that, since once you get to a non-help buffer all unlisted
buffers are skipped, thus you won't encounter another help buffer.

-- 
From "know your smileys":
 2B|^2B	  Message from Shakespeare

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by acc987** [comment]
I'm bumping this issue as this issue persists even in 9.0, patch 1632. Being able to cycle through help buffers with `:bnext` and `:bprevious` would indeed be desirable, right now only `:buffer #` to cycle between the current and alternate (help) buffer.
