### ISSUE TITLE
virtualedit not working with  encoding=utf-8

### ISSUE THREAD

**Issue by m2acgi** [vim/vim#4581]
**Describe the bug**
`set virtualedit=block`  not work when `set encoding=utf-8`.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Set `set encoding=utf-8` and `set virtualedit=block` in **_vimrc**
2. Run `vim --clean` (or `gvim --clean`, etc.)
3. Edit `filename`
4. Type 'ctrl + q', select block, 'shift + a' to append some strings.
5. Only the first line has appended strings.

**Expected behavior**
Append string should appear for all selected lines.

**Screenshots**

**Environment (please complete the following information):**
 - Vim version `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 18:25:27) MS-Windows 32-bit GUI version with OLE support Included patches: 1-2`
 - OS:  Microsoft Windows 7 Ultimate 64bit
 - Terminal: gvim

**Additional context**

**Comment by tonymec** [comment]
A lot of water has passed under the bridge since 12 september 2016, when Vim 8.0.2 was released. Maybe your problem has been fixed since then.

The latest Vim as of this writing is 8.1.1587, and I hope someone can tell you where to get a reasonably recent one for Windows (Steve Hall, who used to publish them, seems to have gone out of business).

Or you can compile your own, see
* https://vim.wikia.com/wiki/Getting_the_Vim_source_with_Mercurial
* http://users.skynet.be/antoine.mechelynck/vim/compile.htm

Best regards,
Tony.

**Comment by m2acgi** [comment]
@tonymec
To test with the latest version of the gvim for Windows, the issue still exists.

- https://github.com/vim/vim-win32-installer/releases/download/v8.1.1587/gvim_8.1.1587_x64.exe

Thanks.

**Comment by k-takata** [comment]
Couldn't reproduce with/without `set enc=utf-8`.

>  4\. Type 'ctrl + q', select block, 'shift + a' to append some strings.

Did you type Esc to leave the insert mode or something else?

**Comment by m2acgi** [comment]
This issue is solved after comment `source $VIMRUNTIME/mswin.vim` and `behave mswin` in the **_vimrc**.

Thank you.

**Comment by m2acgi** [comment]
In some cases still not working. 

![gif](https://user-images.githubusercontent.com/34497122/60159701-64de9a00-9826-11e9-9395-8b1612353772.gif)


[givm](https://github.com/vim/vim-win32-installer/releases/download/v8.1.1587/gvim_8.1.1587_x64.exe)
[ok.txt](https://github.com/vim/vim/files/3328769/ok.txt)
[ko.txt](https://github.com/vim/vim/files/3328770/ko.txt)
