### ISSUE TITLE
color in popup window seems not right

### ISSUE THREAD

**Issue by Yggdroot** [vim/vim#5159]
**Describe the bug**
color in popup window seems not right.
as per the doc,
https://github.com/vim/vim/blob/7a641ca1e113c813fc39cca26f69cd6fc19f71c2/runtime/doc/syntax.txt#L4983-L4994

If the guibg color is set as `NONE`, it indicates "no color (transparent)", but in popup window, the color is the same as `Normal`.

**To Reproduce**
test.vim
```vim
hi Test gui=NONE guibg=NONE guifg=RED cterm=NONE ctermbg=NONE ctermfg=12
let id = popup_create(bufnr('%'), #{line:0, col:0, maxheight:4})
call win_execute(id, "call matchadd('Test', 'popup')")
```
1. so %

**Expected behavior**

The color should be the same as background of popup window.

**Screenshots**
![111](https://user-images.githubusercontent.com/2705841/68030004-74e61900-fcf3-11e9-8054-0b5e0a32884c.png)

**Environment (please complete the following information):**
 - Vim version : 8.1.2168
 - OS:  Windows 7

**Comment by chrisbra** [comment]
I believe you need to set the `wincolor` option to the highlighting group you want to have used. Popup windows seem to use the Pmenu group according to the [documentation](https://vimhelp.org/popup.txt.html):

> The default color used is "Pmenu".  If you prefer something else use the
> "highlight" argument or the 'wincolor' option, e.g.: 
>         hi MyPopupColor ctermbg=lightblue guibg=lightblue
>         call setwinvar(winid, '&wincolor', 'MyPopupColor')

**Comment by Yggdroot** [comment]
@chrisbra I think you did not catch what I mean. I mean `If the guibg color is set as NONE, the guibg should be transparent, i.e., the same as the background.`

**Comment by bfrg** [comment]
It works fine with `8.1.2230`. It must have been fixed somewhere in between.

**Comment by Yggdroot** [comment]
> It works fine with `8.1.2230`. It must have been fixed somewhere in between.

Confirmed. This issue does not exist in 8.1.2238 any more.

But the issue still exists if `set filetype`, e.g.,

```vim
hi Test gui=NONE guibg=NONE guifg=RED cterm=NONE ctermbg=NONE ctermfg=12
let id = popup_create(bufnr('%'), #{line:0, col:0, maxheight:4})
call win_execute(id, 'setlocal filetype=cpp')
call win_execute(id, "call matchadd('Test', 'popup')")
```
