### ISSUE TITLE
Incorrect cursor movement in popup terminal !!

### ISSUE THREAD

**Issue by skywind3000** [vim/vim#5943]
**Describe the bug**

When working in a terminal popup, the cursor moves irregularly.

Popup terminal in Windows GVim:

![popup_term1](https://user-images.githubusercontent.com/3035071/79512850-ea149300-8074-11ea-9464-f57f1b6b5549.gif)

When you input a character, the cursor will move up and down.

Popup terminal in Linux Vim (terminal vim):

![popup_term2](https://user-images.githubusercontent.com/3035071/79512883-fef12680-8074-11ea-8212-d3d284ea8f1b.gif)

Same problem.

But if I disable the popup border, the cursor movement will restore to normal.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.)
2. Edit `popup_term.vim`
3. Type

```VimL
let opts = {'hidden':1, 'term_rows':25, 'term_cols':80, 'term_finish':'close'}
let bid = term_start(has('win32')? 'cmd' : 'bash', opts)

let opts = {'maxwidth':80, 'minwidth':80, 'maxheight':25, 'minheight':25}
let opts.wrap = 0
let opts.border = repeat([1], 9)
let opts.borderchars = ['-', '|', '-', '|', '+', '+', '+', '+']
let wid = popup_create(bid, opts)
```

Than type `:so %`. and input some characters in the popup terminal.

4. Describe the error

When you type characters in the popup window, the cursor will firstly move up for one line in a short time, than move down and display the character you just typed.

This problem is more obvious in GVim than in the Terminal.

**Expected behavior**
Don't move up and down.

**Environment (please complete the following information):**
 - Vim version 8.2.852
 - OS: Windows 10 (GVim) and Debian 10 (Terminal Vim)
 - MinTTY

**Additional context**

If I comment out line 6:

```VimL
" let opts.border = repeat([1], 9)
```

Issue disappeared:

![popup_term3](https://user-images.githubusercontent.com/3035071/79513543-ae7ac880-8076-11ea-92df-3fd723065dd4.gif)

**Comment by skywind3000** [comment]
One more thing, for GVim on Windows, this problem will become more obvious if we enable DirectX before creating the terminal popup:

```VimL
set rop=type:directx
```

**Comment by blayz3r** [comment]
Is it related to this https://github.com/microsoft/terminal/issues/5362

**Comment by chrisbra** [comment]
but then it wouldn't reproduce on linux?

**Comment by skywind3000** [comment]
1. Nothing to do with windows terminal, I can reproduce on linux (see my second gif).
2. Just more noticable on windows GVim with rop=type:directx.
3. Popup border matters.

It seems that there are some position calculation errors when using popup with borders.

**Comment by skywind3000** [comment]
Btw: Vim 8.2.300 works fine. I will do a bisect.

**Comment by lacygoill** [comment]
> Btw: Vim 8.2.300 works fine. I will do a bisect.

I can reproduce even on 8.2.300.  AFAICT, this issue has always existed.  As soon as popup terminals were available, I implemented a mapping to toggle one with a border, and I immediately noticed the cursor briefly jumping around.  I didn't report it because there were many other issues which seemed more important, and I wasn't sure it would be considered a bug.  But I agree with you; it would be nice if the cursor didn't jump around.

**Comment by skywind3000** [comment]
bisect:

```
v8.2.0587: BAD
v8.2.0400: BAD
v8.2.0350: BAD
v8.2.0337: BAD
v8.2.0331: BAD

v8.2.0328: BAD    # problem happens here

v8.2.0327: OK
v8.2.0326: OK
v8.2.0325: OK
v8.2.0300: OK
```

I believe 

- [v8.2.0328: redraw the popup window](https://github.com/vim/vim/releases/tag/v8.2.0328) 

is accountable for this.

**Comment by skywind3000** [comment]
Another possible reason: maybe it happened long long ago, v8.2.0328 added a "redraw" and made it noticable in my case.

@lacygoill , can you still reproduce it if you hide the popup border ??

If so, the problem may be caused by the popup border.

**Comment by lacygoill** [comment]
> @lacygoill, can you still reproduce it if you hide the popup border ??
>
> If so, the problem may be caused by the popup border.

I can still sometimes see the cursor briefly drawn in a wrong position even without a border, but compared to a popup terminal with a border, it's very rare.
So yes, the border is probably amplifying what is usually a rare issue into something much more visible.

**Comment by lacygoill** [comment]
The patch fixed the flickering but now the position of the cursor is constantly off by 1 line and 1 column.  It's right above where it should be.

![gif](https://user-images.githubusercontent.com/8505073/100524790-559e1180-31bb-11eb-878d-bf1be951d837.gif)

**Comment by lacygoill** [comment]
Actually, it seems off by 1 line and 2 columns.

**Comment by lacygoill** [comment]
> Actually, it seems off by 1 line and 2 columns.

I guess the 1 line off is due to the top border which is ignored, and the 2 columns off are due to the left border and to the left padding which are also ignored.

**Comment by Shane-XB-Qian** [comment]
looks 2ed patch 2067 looks fixed this.. fyi.
