### ISSUE TITLE
syntax/tex.vim matches against g:tex_fast using '=~' instead of '=~#' 

### ISSUE THREAD

**Issue by Coacher** [vim/vim#646]
Hello.

g:tex_fast allows some flags that differ only by case, e.g. 'm' and 'M'. When 'ignorecase' is set '=~' operator makes these flags undistinguishable. '=~#' should be used instead.

Please fix.

**Comment by cecamp** [comment]
I addressed this with syntax/tex.vim v92 on Feb 18 -- so this issue should be closed.

**Comment by Coacher** [comment]
Thank you!

**Comment by Coacher** [comment]
Actually, this is not fixed properly yet. While `=~` seem to be replaced with `=~#`, `!~` are still not replaced with `!~#` in some places. Specifically, this still affects `tex_conceal` and its `s` and `S` flags.

Cannot reopen. Please fix.
