### ISSUE TITLE
Vim9: unexpected E1010 error when using printf format in lambda passed to mapnew()

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7664]
**Describe the bug**

In Vim9 script, using `printf()` inside a lambda might raise an unexpected `E1010` error, at the script level.

**To Reproduce**

Run this shell command:

    vim -Nu NONE -S <(cat <<'EOF'
        vim9
        echo [{n: 1, m: 2, s: 'xxx'}]
            ->mapnew((_, v: dict<any>): string => printf('%d:%d:%s',
                v.n,
                v.m,
                substitute(v.s, '.*', 'yyy', '')
                ))
    EOF
    )

`E1010` is raised:

    E1010: Type not recognized:  v.n,            v.m,            substitute(v.s, '.*', 'yyy', '')            )

**Expected behavior**

No error is raised.

**Environment**

 - Vim version: 8.2 Included patches: 1-2332
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(363)

**Additional context**

The issue disappears if the second line is joined with the first one:
```vim
vim9
echo [{n: 1, m: 2, s: 'xxx'}]->mapnew((_, v: dict<any>): string => printf('%d:%d:%s',
        v.n,
        v.m,
        substitute(v.s, '.*', 'yyy', '')
        ))
```
    ['1:2:yyy']

---

The issue disappears if `substitute()` is removed:
```vim
vim9
echo [{n: 1, m: 2, s: 'xxx'}]
    ->mapnew((_, v: dict<any>): string => printf('%d:%d:%s',
        v.n,
        v.m,
        v.s
        ))
```
    ['1:2:xxx']

---

The issue disappears if one of the % item is removed from the printf format:
```vim
vim9
echo [{n: 1, s: 'xxx'}]
    ->mapnew((_, v: dict<any>): string => printf('%d:%s',
        v.n,
        substitute(v.s, '.*', 'yyy', '')
        ))
```
Not sure, but I suspect that – for the issue to be triggered – the number of % items in the printf format must be different than the number of types specified in the lambda.

---

The issue disappears in a `:def` function:
```vim
vim9
def Func()
    echo [{n: 1, m: 2, s: 'xxx'}]
        ->mapnew((_, v: dict<any>): string => printf('%d:%d:%s',
            v.n,
            v.m,
            substitute(v.s, '.*', 'yyy', '')
            ))
enddef
Func()
```
    ['1:2:yyy']

**Comment by brammool** [comment]
I cannot reproduce this problem, perhaps it was already fixed?

**Comment by lacygoill** [comment]
It's weird, because I can still reproduce on 8.2.2361 in Ubuntu 16.04:

    vim -Nu NONE -i NONE -U NONE -S <(cat <<'EOF'
        vim9
        echo [{n: 1, m: 2, s: 'xxx'}]
            ->mapnew((_, v: dict<any>): string => printf('%d:%d:%s',
                v.n,
                v.m,
                substitute(v.s, '.*', 'yyy', '')
                ))
    EOF
    )

![gif](https://user-images.githubusercontent.com/8505073/104815772-e639bb00-5816-11eb-8835-773a3bee2102.gif)

But I can't reproduce in Ubuntu 18.04 in a virtual machine.

In both cases, I've tested with no configuration option at compile time:

    $ make clean && make distclean
    $ ./configure
    $ make

---

In case it helps, here are some logs:

- [valgrind log](https://github.com/vim/vim/files/5824622/valgrind.log)
- [asan log](https://github.com/vim/vim/files/5824621/asan.log)

The asan log was obtained on Ubuntu 16.04.  The valgrind log was obtained on Ubuntu 18.04.

**Comment by dpelle** [comment]
I'm using xubuntu-18.04.5 with vim-8.2.2362.

I ran the command in your above comment and did not observe E1010 (not any other error).
However, when running that command with valgrind, I indeed see use of free memory as in your attached valgrind log file.
So the bug is confirmed.

**Comment by brammool** [comment]
> It's weird, because I can still reproduce on 8.2.2361 in Ubuntu 16.04:
> 
>     vim -Nu NONE -i NONE -U NONE -S <(cat <<'EOF'
>         vim9
>         echo [{n: 1, m: 2, s: 'xxx'}]
>             ->mapnew((_, v: dict<any>): string => printf('%d:%d:%s',
>                 v.n,
>                 v.m,
>                 substitute(v.s, '.*', 'yyy', '')
>                 ))
>     EOF
>     )
> 
> ![gif](https://user-images.githubusercontent.com/8505073/104815772-e639bb00-5816-11eb-8835-773a3bee2102.gif)
> 
> In both cases, I've tested with no configuration option at compile time:
> 
>     $ make clean && make distclean
>     $ ./configure
>     $ make
> 
> But I can't reproduce in Ubuntu 18.04 in a virtual machine.
> 
> ---
> 
> In case it helps, here are some logs:
> 
> - [valgrind log](https://github.com/vim/vim/files/5824622/valgrind.log)
> - [asan log](https://github.com/vim/vim/files/5824621/asan.log)
> 
> The asan log was obtained on Ubuntu 16.04.  The valgrind log was
> obtained on Ubuntu 18.04.

Aha, it's using freed memory.  The body is collected while going over
linebreaks, but the return type isn't.  I'll fix that.

-- 
hundred-and-one symptoms of being an internet addict:
165. You have a web page burned into your glasses

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
