### ISSUE TITLE
command-line sometimes overwrites status line in tmux when 'winminheight' is increased

### ISSUE THREAD

**Issue by lacygoill** [vim/vim#7899]
**Describe the bug**

When Vim is run inside tmux, the command-line might sometimes overwrite the status line when `'winminheight'` is increased.

**To Reproduce**

Open an xterm terminal and run this shell command to reset the terminal height to 12 lines:

    vim -Nu NONE +'set lines=12 | q'

Run this shell command to start a tmux session without any config:

    tmux -Lx -f/dev/null

Run this other shell command to start Vim:

    vim -Nu NONE -S <(cat <<'EOF'
        set wmh=0 stal=2
        bel sp | wincmd _
        bel sp | wincmd _
        bel sp | wincmd _
        bel sp
    EOF
    )

Finally, run this Ex command:

    :set wmh=1

The command-line disappears.  If we press `:` to enter the command-line, it overwrites the status line of the bottom window, which is confusing.

**Expected behavior**

When `wmh` is reset to 1, an error is raised.  The command-line does not disappear, and it does not overwrite the status line of a Vim window.

**Environment**

 - Vim version: 8.2 Included patches: 1-2549
 - OS: Ubuntu 16.04.7 LTS
 - Terminal: xterm(366)

**Additional context**

I think the issue is that – when executing `set wmh=1` – Vim needs more space, and asks the terminal to increase its height by 1 line.  This fails in tmux, but Vim proceeds like it succeeded:

    :echo &lines
    11
    # this is correct; the terminal has indeed 11 lines

    :set wmh=1
    :echo &lines
    12
    # this is NOT correct; the terminal has still 11 lines, not 12

---

After that, Vim is in a weird and confusing state, which looks wrong for so many reasons, I won't try to describe it; instead, here is a gif:

![gif](https://user-images.githubusercontent.com/8505073/109130037-932a2080-7751-11eb-81b3-ebb1025b55ff.gif)

---

There are other similar issues when setting the `'lines'` and `'columns'` option.

I suggest the following: when `&term` contains the string `tmux` (and probably `screen` too), it should not be allowed for Vim to change the terminal geometry.  If it needs to, then it should just raise an error (which we can catch with a try/catch if necessary).

I think it's the simplest fix.  I guess the alternative would be to translate whatever sequences Vim usually sends to the terminal so that tmux relays them to the real outer terminal.  There exists a DCS sequence for that:

    \033Ptmux;\033seq\033\0134
                  ^^^
                  any escape in the original sequence must be doubled

But what if Vim is running in a splitted tmux window (i.e. a tmux pane)?  Not sure changing the terminal geometry is the right approach then.  In that case, I think it's the geometry of the tmux pane which should be changed.  Anyway, it quickly gets too complex; that's why I suggest to just raise an error to avoid Vim ending in a messy state.

**Comment by tonymec** [comment]
Changing `'winminheight'` doesn't change the terminal's geometry, it changes how Vim allocates different parts of the terminal for different uses. `'winminheight'`, for instance, is the minimum allowable height for a split window. The only error increasing it should cause, is if (&wmh + 1) * (number of horisontally split windows) exceeds `'lines'`.

OTOH, changing the `'lines'` and/or `'columns'` settings does change the geometry of the Vim screen. That works in gvim and in some terminals including xterm and konsole. In the non-X linux console the geometry is fixed and unchangeable, it depends on the hardware font and on the VGA mode (on my system it's 48 lines by 128 columns). Other terminal emulators running in a GUI (X11, Windows, etc.) may or may not accept resizing. Under both `'lines'` and `'columns'`, the help mentions that if you try to change these options in a non-resizable terminal, the display wil be messed up.

The t_WS key sequence is used to set the height and width of the Vim screen when running in Console mode. IIUC, if you determine that you are running in a non-resizable terminal, setting that keycode to the empty string will avoid resizing.

Best regards,
Tony.

**Comment by lacygoill** [comment]
> Changing 'winminheight' doesn't change the terminal's geometry,

Sometimes, it does:

    vim -Nu NONE +'set lines=11 | q'

    vim -Nu NONE -S <(cat <<'EOF'
        set wmh=0 stal=2
        bel sp | wincmd _
        bel sp | wincmd _
        bel sp | wincmd _
        bel sp
    EOF
    )

    :echo &lines
    11

    :set wmh=1

    :echo &lines
    12

Notice how the terminal height has increased by 1 line.  Tested in xterm.  But this fails inside tmux.

> The only error increasing it should cause, is if (&wmh + 1) * (number of horisontally split windows) exceeds 'lines'.

I agree; an error should be raised.  But right now, no error is raised.

> Under both 'lines' and 'columns', the help mentions that if you try to change these options in a non-resizable terminal, the display wil be messed up.

Ah, you're right; I missed that part.  Thank you for the information.

> The t_WS key sequence is used to set the height and width of the Vim screen when running in Console mode. IIUC, if you determine that you are running in a non-resizable terminal, setting that keycode to the empty string will avoid resizing.

In this case, it doesn't help; `t_WS` is already empty.

Anyway, I'm closing because the help acknowledges the fact that Vim can be messed up if it's unable to change the number of lines.

**Comment by brammool** [comment]
Having the last status line displayed overlapping with the command line is a bug.
Setting 'winminheight' is not supposed to change the height of the terminal.
The check if there is enough room ignores the tabline, that should be fixed.

**Comment by lacygoill** [comment]
> Setting 'winminheight' is not supposed to change the height of the terminal.

The issue persists when the split windows are in a different tab page:

    vim -Nu NONE -S <(cat <<'EOF'
        set lines=6 wmh=0
        sp
        sp
        tabnew
        echom &lines
        set wmh=1
        echom &lines
    EOF
    )

Notice how the terminal's height is – initially – 6.  But right after `'wmh'` is reset to 1, the terminal's height is increased to 8.  This happens even though the error `E593` is correctly raised.  In practice, it has the exact same effects in tmux; the command line overwrites the status line (because Vim fails to resize the terminal there, but proceeds like it succeeded).
