### ISSUE TITLE
Ctrl+J mapping sometimes does not work in gvim

### ISSUE THREAD

**Issue by user202729** [vim/vim#8792]
**Describe the bug**
Sometimes keymap sequence that use a Ctrl+J key sequence does not work.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `gvim --clean` (does not happen with vim!)
2. `map <c-j> a`
//3. `map <c-j>a <nop>`
3. Press Control+J (in normal mode).
4. *Error*: rather than `^J` or `^@`, the text `<9b>ü^DJ` is displayed on the status bar
5. Now press `b` (before `timeoutlen` expires). The whole sequence `<c-j>b` should translates to `ab` (append b).
6. *Error*: the cursor moves down a line instead

**Expected behavior**
~

**Screenshots**
~

**Environment (please complete the following information):**
 - Vim version 

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2021 06:58:52)
Included patches: 1-2891
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):              
```

 - Terminal: gvim (GUI)

**Additional context**

Also happens with other Ctrl+ keys.

**Comment by lacygoill** [comment]
I noticed [this issue](https://github.com/lacygoill/wiki/blob/master/bug/vim.md#mapping-regression) a long time ago:

    vim -u NONE -U NONE -N -g -S <(cat <<'EOF'
        set guioptions=
        inoremap <c-e> export
        inoremap <c-e><c-s> extends
        startinsert
    EOF
    )

Press CTRL-E then `l`.  We should get `exportl`; but in the GUI and in xterm, we get `l`.
I think it's a regression caused by the patch [8.2.0851](https://github.com/vim/vim/releases/tag/v8.2.0851).

Here is the list of issues where this patch is mentioned (it seems they were all fixed):

https://github.com/vim/vim/issues?q=is%3Aissue+8.2.0851+is%3Aclosed

**Comment by lacygoill** [comment]
In xterm, the issue can be avoided by disabling the modifyOtherKeys feature (`set t_TI= t_TE=`).  But that can't work for the GUI.

**Comment by brammool** [comment]
I cannot reproduce it with the current Vim version.  Not in a terminal and not in the GUI.
Is there some extra condition, or has it been fixed in the mean time?

**Comment by lacygoill** [comment]
I'm on 8.2.4502, and I can still reproduce the issue in the GTK3 GUI:

    $ HOME=/dev/null vim -Nu NONE -U NONE -i NONE -g -S <(tee <<'EOF'
        vim9script
        map <C-J> a
        map <C-J>a <Nop>
        ['one', 'two', 'three']->setline(1)
        normal! $
        feedkeys("\<C-J>b")
    EOF
    )

Expected: the buffer contains these lines:

    oneb
    two
    three

And the cursor is at the end of the first line.

Actual: the buffer contains these lines:

    one
    two
    three

And the cursor is on the second line.

Maybe the issue is specific to GTK3 (and not GTK2)?

**Comment by lacygoill** [comment]
> Maybe the issue is specific to GTK3 (and not GTK2)?

No, it's not specific to GTK3.  I can also reproduce in GTK2.

**Comment by brammool** [comment]
It is specific for executing the commands in the sourced script.
If the last line is replaced with:  ```timer_start(100, (_) => feedkeys("\<C-J>b")```
the problem goes away.
Also, when the commands are typed I cannot reproduce the problem.
Not sure if we need to care of handling mappings while starting up.

**Comment by lacygoill** [comment]
> If the last line is replaced with: timer_start(100, (_) => feedkeys("\<C-J>b")
   > the problem goes away.

Yes, although not sure why the timer has such an effect here.

   > Also, when the commands are typed I cannot reproduce the problem.

When typing the commands interactively, I can still reproduce the issue in the GUI, and in a terminal when modifyOtherKeys is enabled:

    HOME=/dev/null vim -Nu NONE -U NONE -i NONE -g --cmd 'set t_TI= t_TE=' -S <(tee <<'EOF'
        vim9script
        map <C-J> a
        map <C-J>a <Nop>
        ['one', 'two', 'three']->setline(1)
        normal! $
    EOF
    )

**Comment by lacygoill** [comment]
> and in a terminal when modifyOtherKeys is enabled:

Sorry, I meant when modifyOtherKeys is disabled (not enabled).

**Comment by lacygoill** [comment]
> Sorry, I meant when modifyOtherKeys is disabled (not enabled).

No, something else is going on, but I'm not sure what it is.  Sometimes I can reproduce, sometimes I cannot.  I need more time to do more tests.

**Comment by lacygoill** [comment]
OK, so in the terminal, the issue is influenced by the modifyOtherKeys feature.  It needs to be enabled for the issue to be reproduced.

So, this command is working fine:

    HOME=/dev/null vim -Nu NONE -U NONE -i NONE --cmd 'set t_TI= t_TE=' -S <(tee <<'EOF'
        vim9script
        map <C-J> a
        map <C-J>a <Nop>
        ['one', 'two', 'three']->setline(1)
        normal! $
    EOF
    )

But this one does not:

    HOME=/dev/null vim -Nu NONE -U NONE -i NONE --cmd 'execute "set t_TI=\<Esc>[>4;2m t_TE=\<Esc>[>4;m"' -S <(tee <<'EOF'
        vim9script
        map <C-J> a
        map <C-J>a <Nop>
        ['one', 'two', 'three']->setline(1)
        normal! $
    EOF
    )

Here is a gif to illustrate:

![gif](https://user-images.githubusercontent.com/8505073/156818817-65f68aed-df70-4733-a2c1-29a755a42630.gif)

---

Here is another command which doesn't work (probably because of the exact same issue):

    HOME=/dev/null vim -Nu NONE -U NONE -i NONE --cmd 'execute "set t_TI=\<Esc>[>4;2m t_TE=\<Esc>[>4;m"' -S <(cat <<'EOF'
        vim9script
        inoremap <c-e> export
        inoremap <c-e><c-s> extends
        startinsert
    EOF
    )

Type `<C-E>` then `l`.
Expected: the buffer contains `exportl`.
Actual: the buffer contains `l`.

Here is another gif to illustrate:

![gif](https://user-images.githubusercontent.com/8505073/156818964-e8de3cbe-474d-4269-8423-fd2cd99c314c.gif)

---

Same issue in the GUI.

**Comment by brammool** [comment]
It is tricky, not sure why I can't always reproduce, depending on when the mappings are defined.
I did manage to reproduce it in a debugger and see what happens: when there is a partial map the modifiers are simplified, and then another try is made to find a mapping, but then the original mapping, which uses a separate modifier, will no longer match.
I can make this work, but it might cause another problem...
