### ISSUE TITLE
Regression: :insert in empty buffer creates jump to line 2 (after 7.4.1896)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#892]
My automated tests caught a regression caused by

>    Date:   2016-06-04 20:14:07 +0200
>    patch 7.4.1896
>    Problem:    Invoking mark_adjust() when adding a new line below the last line
>                 is pointless.
>    Solution:   Skip calling mark_adjust() when appending below the last line.

Beforehand, `:insert` on an empty buffer positioned the jump mark from line 1 to (invalid) line 5, now it's positioned on line 2 (i.e. right in the middle of the edit, which doesn't make sense!)
### Reproduce

Create a file `record`:

```
:insert
foo
bar
baz
quux
.
:if line("''") == 5 | quit! | else | cquit! | endif
```

Run:

```
$ ./src/vim -N -u NONE -s record
```
### Discussion

Actually, I think both old and new behaviors are wrong. In my mind, `:insert` should _always_ behave just like `i`, and not create a jump at all. (It does not create jumps when executed in a non-empty buffer.)

**Comment by vim-ml** [comment]
On Thu, Jun 30, 2016 at 6:07 PM, Ingo Karkat vim-dev-github@256bit.org wrote:

> My automated tests caught a regression caused by
> 
> Date: 2016-06-04 20:14:07 +0200
> patch 7.4.1896
> Problem: Invoking mark_adjust() when adding a new line below the last line
> is pointless.
> Solution: Skip calling mark_adjust() when appending below the last line.
> 
> Beforehand, :insert on an empty buffer positioned the jump mark from line 1
> to (invalid) line 5, now it's positioned on line 2 (i.e. right in the middle
> of the edit, which doesn't make sense!)
> 
> Reproduce
> 
> Create a file record:
> 
> :insert
> foo
> bar
> baz
> quux

When reporting a problem, please check beforehand if it still exists
in the latest version. See
http://ftp.vim.org/pub/vim/patches/7.4/README (or the same over
ftp://...) for a one-line summary of every patch published so far for
Vim 7.4.

I cannot reproduce this in gvim 7.4.1967 (Huge, with GTK2/Gnome GUI)
i.e. 71 patchlevels later.

When I terminate the :insert command by entering a line consisting
only of a period, the cursor is now positioned on the last line i.e.
on the q of quux.

Best regards,
Tony.

**Comment by inkarkat** [comment]
Tony, I can still reproduce this with the latest Vim 7.4.1967.

> When I terminate the :insert command by entering a line consisting only of a period, the cursor is now positioned on the last line i.e. on the q of quux.

The problem is not with the cursor position, it's with the jump mark (`''`).  (I wrote _creates jump_, not _jumps_; sorry if that was too obscure to notice.) After `:insert`, execute `:marks` (or jump back with `<C-O>`):

```
:marks
mark line  col file/text
'      2    0 bar
"      1    0 foo
[      1    0 foo
]      4    0 quux
.      4    0 quux
```

In previous Vim versions, it was this:

```
:marks
mark line  col file/text
'      5    0 -invalid-
```

I'd argue it should be this instead:

```
:marks
mark line  col file/text
'      1    0 foo
```

**Comment by chrisbra** [comment]
So the problem only happens for empty initial buffers? In that case, there shouldn't be any marks there anyhow, right? So this patch should fix it:

``` patch
diff --git a/src/misc1.c b/src/misc1.c
index 7969968..19537b7 100644
--- a/src/misc1.c
+++ b/src/misc1.c
@@ -2866,8 +2866,9 @@ appended_lines_mark(linenr_T lnum, long count)
 {
     /* Skip mark_adjust when adding a line after the last one, there can't
      * be marks there. */
-    if (lnum + count < curbuf->b_ml.ml_line_count)
-       mark_adjust(lnum + 1, (linenr_T)MAXLNUM, count, 0L);
+    if (lnum + count < curbuf->b_ml.ml_line_count &&
+           !curbuf->b_ml.ml_flags & ML_EMPTY)
+       mark_adjust(lnum, (linenr_T)MAXLNUM, count, 0L);
     changed_lines(lnum + 1, 0, lnum + 1, count);
 }

```

**Comment by inkarkat** [comment]
Thanks @chrisbra! Yes, that seems to do the trick. The jump mark now isn't changed, and remains at the initial line 1 col 0, as I would expect.

**Comment by brammool** [comment]
Christian Brabandt wrote:

> So the problem only happens for empty initial buffers? In that case,
> there shouldn't be any marks there anyhow, right? So this patch should
> fix it:
> 
> ``` c
> diff --git a/src/misc1.c b/src/misc1.c
> index 7969968..19537b7 100644
> --- a/src/misc1.c
> +++ b/src/misc1.c
> @@ -2866,8 +2866,9 @@ appended_lines_mark(linenr_T lnum, long count)
>  {
>      /* Skip mark_adjust when adding a line after the last one, there can't
>       * be marks there. */
> -    if (lnum + count < curbuf->b_ml.ml_line_count)
> -       mark_adjust(lnum + 1, (linenr_T)MAXLNUM, count, 0L);
> +    if (lnum + count < curbuf->b_ml.ml_line_count &&
> +           !curbuf->b_ml.ml_flags & ML_EMPTY)
> +       mark_adjust(lnum, (linenr_T)MAXLNUM, count, 0L);
>      changed_lines(lnum + 1, 0, lnum + 1, count);
>  }
> 
> ```

That doesn't appear to fix the problem.

Why did you change "lnum + 1" to "lnum"?  That doesn't seem right.

## 

"Hit any key to continue" is a lie.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Ingo Karkat wrote:

> My automated tests caught a regression caused by
> 
> >    Date:   2016-06-04 20:14:07 +0200
> >    patch 7.4.1896
> >    Problem:    Invoking mark_adjust() when adding a new line below the last line
> >                 is pointless.
> >    Solution:   Skip calling mark_adjust() when appending below the last line.
> 
> Beforehand, `:insert` on an empty buffer positioned the jump mark from line 1 to (invalid) line 5, now it's positioned on line 2 (i.e. right in the middle of the edit, which doesn't make sense!)
> 
> ### Reproduce
> 
> Create a file `record`:
> 
> ```
> :insert
> foo
> bar
> baz
> quux
> .
> :if line("''") == 5 | quit! | else | cquit! | endif
> ```
> 
> Run:
> 
> ```
> $ ./src/vim -N -u NONE -s record
> ```
> 
> ### Discussion
> 
> Actually, I think both old and new behaviors are wrong. In my mind,
> `:insert` should _always_ behave just like `i`, and not create a jump
> at all. (It does not create jumps when executed in a non-empty
> buffer.)

It doesn't create a jump, the original position is on the empty line
that's in the empty buffer.  The first new line is inserted above it,
causing marks in line 1 to be moved down one line.

I'll make it so that marks are not moved down.

## 

Apathy Error: Don't bother striking any key.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
@brammool  that was wrong from testing. sorry for that. I meant to only update the if condition.

**Comment by vim-ml** [comment]
Hello, 

I feel wonderful, just better than ever and all that  thanks to a  great book I've read  recently! You  may also  read it  here <http://together.catchyvoices.com/e4vxvtq>

See you around, paul
