### ISSUE TITLE
'virtualedit' and tabulation affect number increment/decrement

### ISSUE THREAD

**Issue by xaizek** [vim/vim#923]
Run Vim like this:

```
vim -N -u NONE -c 'set virtualedit=all'
```

Enter the following text:

```
<tabulation>1
```

See how cursor position relative to tabulation affects placement of incremented/decremented number:

```
" "|" designates cursor position
|       1
" <ctrl-x> gives this (OK)
|       0
" moving cursor to the right before pressing <ctrl-x> moves number (not OK)
 |       -1
  |       -2
   |       -3
" etc.
```

Virtual space seems to be counted as if it was a real character.

**Comment by vim-ml** [comment]
Hi xaizek and list,

2016-7-15(Fri) 2:30:56 UTC+9 xaizek:

> Run Vim like this:
> 
> vim -N -u NONE -c 'set virtualedit=all'
> 
> Enter the following text:
> 
> <tabulation>1
> 
> See how cursor position relative to tabulation affects placement of incremented/decremented number:
> 
> " "|" designates cursor position
> |       1
> " <ctrl-x> gives this (OK)
> |       0
> " moving cursor to the right before pressing <ctrl-x> moves number (not OK)
>  |       -1
>   |       -2
>    |       -3
> " etc.
> 
> Virtual space seems to be counted as if it was a real character.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, .

I can reproduce your reported issue.

And I also found a bug that involved to increment/decrement with vitrual edit.

How to reproduce:
- Start naked Vim with virtualedit.
  $ vim -Nu NONE -c "set ve=all"
- Input buffer to `3`
  i3<Esc>
- Cursor move to the right edge.
  g$
- Do increment.
  <C-A>

Expected result:
- Buffer is not changed.

Actual result:
- Number was incremented and move to before the right edge.

I'll investigate these issues on this weekend or next.
I have wrote some patches involved to CTRL-A and CTRL-X.
e.g.
https://github.com/vim/vim/commit/d79e55016cf8268cee935f1ac3b5b28712d1399e

## Thanks.

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
On Fr, 15 Jul 2016, h_east wrote:

> Hi xaizek and list,
> 
> 2016-7-15(Fri) 2:30:56 UTC+9 xaizek:
> 
> > Run Vim like this:
> > 
> > vim -N -u NONE -c 'set virtualedit=all'
> > 
> > Enter the following text:
> > 
> > <tabulation>1
> > 
> > See how cursor position relative to tabulation affects placement of incremented/decremented number:
> > 
> > " "|" designates cursor position
> > |       1
> > " <ctrl-x> gives this (OK)
> > |       0
> > " moving cursor to the right before pressing <ctrl-x> moves number (not OK)
> >  |       -1
> >   |       -2
> >    |       -3
> > " etc.
> > 
> > Virtual space seems to be counted as if it was a real character.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, .
> 
> I can reproduce your reported issue.

Yeah, the problem is, that ins_str() changes the buffer and actually
inserts blanks, if the cursor is beyond the line end.

I tried this patch:

``` diff
--- a/src/ops.c
+++ b/src/ops.c
@@ -5835,7 +5835,18 @@ do_addsub(
                *ptr++ = '0';
        *ptr = NUL;
        STRCAT(buf1, buf2);
+#ifdef FEAT_VIRTUALEDIT
+       if (virtual_active())
+       {
+           save_cursor = curwin->w_cursor;
+           curwin->w_cursor.coladd = 0;
+       }
+#endif
        ins_str(buf1);          /* insert the new number */
+#ifdef FEAT_VIRTUALEDIT
+       if (virtual_active())
+           curwin->w_cursor.coladd = save_cursor.coladd;
+#endif
        vim_free(buf1);
        endpos = curwin->w_cursor;
        if (did_change && curwin->w_cursor.col)
```

this almost works, except that after incrementing/decrementing ml_get()
still returns the wrong line. I don't know why yet.

On the other hand, one could argue, that the number shouldn't be 
incremented/decremented at all if the cursor is actually not on a 
number, so you could even consider the successful increment to be a bug.

I don't know.

Best,

## Christian

Radio:
  in manchen Kreisen wurden mit Radios umfangreiche Berechnungen
  angestellt

**Comment by vim-ml** [comment]
Hi xaizek, ChrisB and Bram,

2016-7-16(Sat) 2:08:47 UTC+9 vim-dev ML:

> On Fr, 15 Jul 2016, h_east wrote:
> 
> > Hi xaizek and list,
> > 
> > 2016-7-15(Fri) 2:30:56 UTC+9 xaizek:
> > 
> > > Run Vim like this:
> > > 
> > > vim -N -u NONE -c 'set virtualedit=all'
> > > 
> > > Enter the following text:
> > > 
> > > <tabulation>1
> > > 
> > > See how cursor position relative to tabulation affects placement of incremented/decremented number:
> > > 
> > > " "|" designates cursor position
> > > 
> > > |       1
> > > 
> > > " <ctrl-x> gives this (OK)
> > > 
> > > |       0
> > > 
> > > " moving cursor to the right before pressing <ctrl-x> moves number (not OK)
> > > 
> > >  |       -1
> > > 
> > >   |       -2
> > > 
> > >    |       -3
> > > 
> > > " etc.
> > > 
> > > Virtual space seems to be counted as if it was a real character.
> > > 
> > > —
> > > 
> > > You are receiving this because you are subscribed to this thread.
> > > 
> > > Reply to this email directly, view it on GitHub, .
> > 
> > I can reproduce your reported issue.
> 
> Yeah, the problem is, that ins_str() changes the buffer and actually
> 
> inserts blanks, if the cursor is beyond the line end.
> 
> I tried this patch:
> 
> ``` diff
> 
> --- a/src/ops.c
> 
> +++ b/src/ops.c
> 
> @@ -5835,7 +5835,18 @@ do_addsub(
> 
>                 *ptr++ = '0';
> 
>         *ptr = NUL;
> 
>         STRCAT(buf1, buf2);
> 
> +#ifdef FEAT_VIRTUALEDIT
> 
> +       if (virtual_active())
> 
> +       {
> 
> +           save_cursor = curwin->w_cursor;
> 
> +           curwin->w_cursor.coladd = 0;
> 
> +       }
> 
> +#endif
> 
>         ins_str(buf1);          /* insert the new number */
> 
> +#ifdef FEAT_VIRTUALEDIT
> 
> +       if (virtual_active())
> 
> +           curwin->w_cursor.coladd = save_cursor.coladd;
> 
> +#endif
> 
>         vim_free(buf1);
> 
>         endpos = curwin->w_cursor;
> 
>         if (did_change && curwin->w_cursor.col)
> 
> ```
> 
> this almost works, except that after incrementing/decrementing ml_get()
> 
> still returns the wrong line. I don't know why yet.
> 
> On the other hand, one could argue, that the number shouldn't be 
> 
> incremented/decremented at all if the cursor is actually not on a 
> 
> number, so you could even consider the successful increment to be a bug.

ChrisB>
Your patch is a good hint for me. Thanks!

I wrote a patch with a test.
Please check and include this.

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by vim-ml** [comment]
Hirohito Higashi wrote:

[...]

> > this almost works, except that after incrementing/decrementing ml_get()
> > still returns the wrong line. I don't know why yet.
> > 
> > On the other hand, one could argue, that the number shouldn't be 
> > incremented/decremented at all if the cursor is actually not on a 
> > number, so you could even consider the successful increment to be a bug.
> 
> ChrisB>
> Your patch is a good hint for me. Thanks!
> 
> I wrote a patch with a test.
> Please check and include this.

Thanks!

## 

God made machine language; all the rest is the work of man.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Was this fixed?  There is mention of a fix, thus I suspect it was fixed.

**Comment by xaizek** [comment]
Just checked on Vim 8.2.909, the bug is still there. I guess the patch wasn't applied.

**Comment by chrisbra** [comment]
The patch is here: https://groups.google.com/d/msg/vim_dev/eCtwsQw0f7I/Of_20pacBgAJ

Can you try to apply it and see if this works? It also contains a test to fix this.

**Comment by xaizek** [comment]
It doesn't work and the test fails. Here is the patch updated to cleanly apply on 2d4070d3b02e775a6f3d5ef52265add270e09a4f: [fix_increment_with_virtualedit_updated.txt](https://github.com/vim/vim/files/4765461/fix_increment_with_virtualedit_updated.txt) (github doesn't like `.patch` extension...).

**Comment by chrisbra** [comment]
> fix_increment_with_virtualedit_updated.txt (github doesn't like .patch extension...).

That file contains  ANSI escape sequences and I could not apply it. I have a suspicion, that the problem is the `#ifdef FEAT_VIRTUALEDIT`. That feature has been graduated to be always included as of 8.1.826, so I suspect the patch is actually not really included. 

I'll applied it locally, and the test seems to pass and also the original bug report at the top also seems to be fixed. Please check, PR coming in just a minute. I also notice the help mentions, `not available when compiled without the  |+virtualedit| feature`, so I also updated the help documents slightly.

**Comment by xaizek** [comment]
Sorry, I don't know why `git` uses external diff even when output is redirected. I tested your branch and can confirm that it fixes the issue and the new test passes.

**Comment by chrisbra** [comment]
> Sorry, I don't know why git uses external diff even

you might need `--no-ext-diff` argument for git.

thanks for confirming it works.! 👍

**Comment by xaizek** [comment]
> you might need `--no-ext-diff` argument for git.

I need it to stop using external diff with redirection precisely because I forget about adding `--no-ext-diff` :)

Thanks for the fix.

**Comment by lacygoill** [comment]
Since the issue was fixed, then this todo item is no longer relevant:

https://github.com/vim/vim/blob/21829c5f2c86cd525c8468121b4fc54c5d75bf6e/runtime/doc/todo.txt#L1136-L1138

As for the question:

> Was this fixed?

Yes, it was.  I can't reproduce on master.
