### ISSUE TITLE
vim9script: error when using method call syntax for imported function

### ISSUE THREAD

**Issue by bfrg** [vim/vim#9496]
### Steps to reproduce

Run `vim --clean -S test.vim` with the following two files:

File `script.vim`:
```vim
vim9script
export def Test(n: number)
    echo n
enddef
```

File `test.vim`:
```vim
vim9script
import './script.vim'
bufnr()->script.Test()
```

Result:
```
Error detected while processing /tmp/test.vim:
line    3:
E107: Missing parentheses: script.Test()
```

On the other hand, the following `test.vim` (without method call syntax) works as expected:
```vim
vim9script
import './script.vim'
script.Test(bufnr())
```

### Expected behaviour

No errors

### Version of Vim

8.2.4049

### Environment

Linux

**Comment by bfrg** [comment]
I tried calling the function through a reference but that gives me another error:
```vim
vim9script
import './script.vim'
const Test = script.Test
bufnr()->Test()
```

Result:
```
E119: Not enough arguments for function: <80><fd>R102_Test
```

**Comment by Bakudankun** [comment]
Hi, @brammool and @bfrg 

Is it natural to treat `bufnr()->script.Test()` as `bufnr()->(script.Test)()`? Is that mean `.` has priority to `->` expression? They are both expr8 according to the help doc.

Also, `'string'->dict.func()` does not work in legacy script. Should it work?

I don't have much objection about this change, since I know `->` in Vim script is more a pipe. Maybe what should be fixed is the help doc.

FYI `bufnr()->(script.Test)()` works as expected from before.

**Comment by bfrg** [comment]
When the method call syntax is used inside a `def` function, I'm still getting the same error as before:
```vim
vim9script
import './script.vim'

def Foo()
    bufnr()->script.Test()
enddef
defcompile
```

Result:
```
E107: Missing parentheses: script.Test()
```

---

The second example from above doesn't work yet either:
```vim
vim9script
import './script.vim'
const Test = script.Test
bufnr()->Test()
```

**Comment by brammool** [comment]
> Hi, @brammool and @bfrg 
> 
> Is it natural to treat `bufnr()->script.Test()` as
> `bufnr()->(script.Test)()`? Is that mean `.` has priority to `->`
> expression? They are both expr8 according to the help doc.

They have the same priority, in which case evaluation is from left to
right.  Also, when using "->" what follows must be a function reference,
then an open parenthesis.  I don't think there can be any confusion.

> Also, `'string'->dict.func()` does not work in legacy script. Should
> it work?

It probably should.  More general, any funcion reference should work.  I
currently made a solution very specific for the example, but made a note
about looking into a more generic solution.

> I don't have much objection about this change, since I know `->` in
> Vim script is more a pipe. Maybe what should be fixed is the help doc.
> 
> FYI `bufnr()->(script.Test)()` works as expected from before.

Which also hints at evaluating "script.Test" by itself.  So after "->"
we search for the opening parenthesis, and what is in between should
evaluate to a function name or reference.  This could also work for a
list member:

	var l: list<func>
	....
	bufnr()->l[2]()

-- 
We do not stumble over mountains, but over molehills.
				Confucius

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
The example with "bufnr()->Test()" was a different problem, not counting the base when checking the funcref argument types.
Fixed by 8.2.4114

**Comment by lacygoill** [comment]
> The example with "bufnr()->Test()" was a different problem, not counting the base when checking the funcref argument types.
   > Fixed by 8.2.4114

It's fixed at the script level, but not in compiled code:
```vim
vim9script
var dir = '/tmp/import'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Foo(arg: any)
        echomsg arg
    enddef
END
lines->writefile(dir .. '/script.vim')
import '/tmp/import/script.vim'
def Bar()
    'string'->script.Foo()
enddef
Bar()
```
    E107: Missing parentheses: script.Foo()

Adding parentheses does not help; but it changes the error message:
```vim
vim9script
var dir = '/tmp/import'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Foo(arg: any)
        echomsg arg
    enddef
END
lines->writefile(dir .. '/script.vim')
import '/tmp/import/script.vim'
def Bar()
    'string'->(script.Foo())
enddef
Bar()
```
    E107: Missing parentheses:

The error message gives less information.

**Comment by lacygoill** [comment]
> Adding parentheses does not help; but it changes the error message:

My bad.  I did not position the parentheses correctly.  This works:
```vim
vim9script
var dir = '/tmp/import'
dir->mkdir('p')
var lines =<< trim END
    vim9script
    export def Foo(arg: any)
        echomsg arg
    enddef
END
lines->writefile(dir .. '/script.vim')
import '/tmp/import/script.vim'
def Bar()
    'string'->(script.Foo)()
enddef
Bar()
```
    string

Still not sure whether there is a bug.  The fact that we don't need parentheses at the script level suggests that there is.

**Comment by lacygoill** [comment]
> Still not sure whether there is a bug. The fact that we don't need parentheses at the script level suggests that there is.

Yes, there are.  I'll open separate issues later.

**Comment by lacygoill** [comment]
> Yes, there are.  I'll open separate issues later.

They might have been just fixed by 8.2.4115.  I'll make new tests after updating.

**Comment by lacygoill** [comment]
> They might have been just fixed by 8.2.4115.  I'll make new tests after updating.

No, they are still there as of 8.2.4115.

**Comment by lacygoill** [comment]
Ah, there is a TODO item, so they're probably known issues:
<https://github.com/vim/vim/blob/c665dabdf4c49a0fbf1dc566253c75c2abe2effa/src/testdir/test_vim9_expr.vim#L3169>

---

Basically, there is still an unexpected error in compiled code:

    expr->script.Func()

Which gives:

    Error detected while compiling function ...
    E107: Missing parentheses: script.Func()

Also when using parentheses:

    expr->(script.Func)()
    E121: Undefined variable: g:script#Func

At some point, I thought there was also a separate issue when the method was split on a different line than the base:

    expr
        ->script.Func()

But I don't think that's the case.  At least its seems to give the same unexpected error as when the lines are merged.

**Comment by brammool** [comment]
Hopefully 8.2.4116 takes care of this.  Let me know if there is still some remaining.

**Comment by bfrg** [comment]
The above bugs I reported have been fixed, thank you.

But I'm still getting an error when an imported function is directed to another function using the method call syntax. For example:

File `script.vim`:
```vim
vim9script
export def Square(items: list<number>): list<number>
    return map(items, (_, i) => i * i)
enddef
```

File `test.vim`:
```vim
vim9script
import './script.vim'

def Test()
    echo range(5)
    ->script.Square()
    ->map((_, i) => i * 10)
enddef

Test()
```

Result:
```
Error detected while compiling /tmp/test.vim[10]..function <SNR>1_Test:
line    3:
E107: Missing parentheses:
```

Calling the function through a function reference works though:
```vim
vim9script
import './script.vim'

def Test()
    const Square = script.Square
    echo range(5)
    ->Square()
    ->map((_, i) => i * 10)
enddef

Test()
```

Tested with Vim `8.2.4118`.
